--------------------------------------------------------
-- 模板信息表
--------------------------------------------------------
DROP TABLE IF EXISTS `SYS_TEMPLATE`;
CREATE TABLE `SYS_TEMPLATE` (
    `SID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `C_NAME` VARCHAR(300) COMMENT '模板名称',
    `C_CONTENT` LONGTEXT COMMENT '模板发布后的中间结果',
    `R_CREATE` INT(11) COMMENT '创建人编号',
    `S_CREATE` VARCHAR(50) COMMENT '创建人',
    `T_CREATE` DATETIME COMMENT '创建时间',
    `R_UPDATE` INT(11) COMMENT '更新人编号',
    `S_UPDATE` VARCHAR(50) COMMENT '更新人',
    `T_UPDATE` TIMESTAMP NOT NULL COMMENT '更新时间',
    `R_TENANT` INT(11) COMMENT '租户编号',
    `S_TENANT` VARCHAR(300) COMMENT '租户名称',
    `P_TENANT` CHAR(1) COMMENT '租户类型',
    `N_STATE` INT(11) COMMENT '状态',
    `B_DELETE` CHAR(1) COMMENT '删除标志',
    `N_INDEX` INT(11) COMMENT '排序',
    `N_VERSION` INT(11) COMMENT '版本',
  PRIMARY KEY (`SID`)
);

--------------------------------------------------------
-- 达标体系目录表
--------------------------------------------------------
DROP TABLE IF EXISTS `SYS_STDTMP_FOLDER`;
CREATE TABLE `SYS_STDTMP_FOLDER` (
    `SID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `C_NAME` VARCHAR(300) COMMENT '文件夹名称',
    `R_TEMPLATE` INT(11) COMMENT '所属模板SID',
    `R_SID` INT(11) DEFAULT '0' COMMENT '父文件夹',
    `C_DESC` VARCHAR(2000) COMMENT '描述',
    `C_LOGO` VARCHAR(200) COMMENT 'LOGO图',
    `R_CREATE` INT(11) COMMENT '创建人编号',
    `S_CREATE` VARCHAR(50) COMMENT '创建人',
    `T_CREATE` DATETIME COMMENT '创建时间',
    `R_UPDATE` INT(11) COMMENT '更新人编号',
    `S_UPDATE` VARCHAR(50) COMMENT '更新人',
    `T_UPDATE` TIMESTAMP NOT NULL COMMENT '更新时间',
    `R_TENANT` INT(11) COMMENT '租户编号',
    `S_TENANT` VARCHAR(300) COMMENT '租户名称',
    `P_TENANT` CHAR(1) COMMENT '租户类型',
    `N_STATE` INT(11) COMMENT '状态',
    `B_DELETE` CHAR(1) COMMENT '删除标志',
    `N_INDEX` INT(11) COMMENT '排序',
    `N_VERSION` INT(11) COMMENT '版本',
  PRIMARY KEY (`SID`)
);

--------------------------------------------------------
-- 达标体系文件表
--------------------------------------------------------
DROP TABLE IF EXISTS `SYS_STDTMP_FILE`;
CREATE TABLE `SYS_STDTMP_FILE` (
    `SID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `C_NAME` VARCHAR(300) COMMENT '名称',
    `C_DESC` VARCHAR(2000) COMMENT '描述',
    `R_TEMPLATE` INT(11) COMMENT '所属模板',
    `R_SID` INT(11) COMMENT '所属文件夹SID',
    `S_NAME` VARCHAR(300) COMMENT '所属文件夹名称',
    `B_REMIND` CHAR(1) DEFAULT '1' COMMENT '是否提醒',
    `N_CYCLE` INT(11) COMMENT '更新周期（数量）',
    `P_CYCLE` VARCHAR(32) COMMENT '周期单位SID',
    `S_CYCLE` VARCHAR(100) COMMENT '周期单位名称',
    `C_EXPLAIN` VARCHAR(2000) COMMENT '政策解读',
    `P_TMPFILE` VARCHAR(32) COMMENT '文件类型编码',
    `S_TMPFILE` VARCHAR(100) COMMENT '文件类型名称',
    `R_CREATE` INT(11) COMMENT '创建人编号',
    `S_CREATE` VARCHAR(50) COMMENT '创建人',
    `T_CREATE` DATETIME COMMENT '创建时间',
    `R_UPDATE` INT(11) COMMENT '更新人编号',
    `S_UPDATE` VARCHAR(50) COMMENT '更新人',
    `T_UPDATE` TIMESTAMP NOT NULL COMMENT '更新时间',
    `R_TENANT` INT(11) COMMENT '租户编号',
    `S_TENANT` VARCHAR(300) COMMENT '租户名称',
    `P_TENANT` CHAR(1) COMMENT '租户类型',
    `N_STATE` INT(11) COMMENT '状态',
    `B_DELETE` CHAR(1) COMMENT '删除标志',
    `N_INDEX` INT(11) COMMENT '排序',
    `N_VERSION` INT(11) COMMENT '版本',
  PRIMARY KEY (`SID`)
);

--------------------------------------------------------
-- 模板文件大文本存储表
--------------------------------------------------------
DROP TABLE IF EXISTS `SYS_TEMPLATE_TEXT`;
CREATE TABLE `SYS_TEMPLATE_TEXT` (
    `SID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `R_TEMPLATE` INT(11) NOT NULL DEFAULT '0' COMMENT '所属模板',
    `P_TMPFILE` VARCHAR(32) NOT NULL COMMENT '模板文件类型代码',
    `R_SID` INT(11) COMMENT '对应记录ID',
    `C_CONTENT` LONGTEXT COMMENT '内容',
    `R_CREATE` INT(11) COMMENT '创建人编号',
    `S_CREATE` VARCHAR(50) COMMENT '创建人',
    `T_CREATE` DATETIME COMMENT '创建时间',
    `R_UPDATE` INT(11) COMMENT '更新人编号',
    `S_UPDATE` VARCHAR(50) COMMENT '更新人',
    `T_UPDATE` TIMESTAMP NOT NULL COMMENT '更新时间',
    `R_TENANT` INT(11) COMMENT '租户编号',
    `S_TENANT` VARCHAR(300) COMMENT '租户名称',
    `P_TENANT` CHAR(1) COMMENT '租户类型',
    `N_STATE` INT(11) COMMENT '状态',
    `B_DELETE` CHAR(1) COMMENT '删除标志',
    `N_INDEX` INT(11) COMMENT '排序',
    `N_VERSION` INT(11) COMMENT '版本',
  PRIMARY KEY (`SID`)
);

/**************************************************************************/

--------------------------------------------------------
-- 模板信息归档表
--------------------------------------------------------
DROP TABLE IF EXISTS `SYS_TEMPLATE_ARCH`;
CREATE TABLE `SYS_TEMPLATE_ARCH` (
    `UID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '内部ID',
    `SID` INT(11) COMMENT '归档前的ID',
    `C_NAME` VARCHAR(300) COMMENT '模板名称',
    `C_CONTENT` LONGTEXT COMMENT '模板发布后的中间结果',
    `R_CREATE` INT(11) COMMENT '创建人编号',
    `S_CREATE` VARCHAR(50) COMMENT '创建人',
    `T_CREATE` DATETIME COMMENT '创建时间',
    `R_UPDATE` INT(11) COMMENT '更新人编号',
    `S_UPDATE` VARCHAR(50) COMMENT '更新人',
    `T_UPDATE` TIMESTAMP NOT NULL COMMENT '更新时间',
    `R_TENANT` INT(11) COMMENT '租户编号',
    `S_TENANT` VARCHAR(300) COMMENT '租户名称',
    `P_TENANT` CHAR(1) COMMENT '租户类型',
    `N_STATE` INT(11) COMMENT '状态',
    `B_DELETE` CHAR(1) COMMENT '删除标志',
    `N_INDEX` INT(11) COMMENT '排序',
    `N_VERSION` INT(11) COMMENT '版本',
  PRIMARY KEY (`UID`)
);

--------------------------------------------------------
-- 达标体系目录归档表
--------------------------------------------------------
DROP TABLE IF EXISTS `SYS_STDTMP_FOLDER_ARCH`;
CREATE TABLE `SYS_STDTMP_FOLDER_ARCH` (
    `UID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '内部ID',
    `SID` INT(11) COMMENT '归档前的ID',
    `C_NAME` VARCHAR(300) COMMENT '文件夹名称',
    `R_TEMPLATE` INT(11) COMMENT '所属模板SID',
    `R_SID` INT(11) DEFAULT '0' COMMENT '父文件夹',
    `C_DESC` VARCHAR(2000) COMMENT '描述',
    `C_LOGO` VARCHAR(200) COMMENT 'LOGO图',
    `R_CREATE` INT(11) COMMENT '创建人编号',
    `S_CREATE` VARCHAR(50) COMMENT '创建人',
    `T_CREATE` DATETIME COMMENT '创建时间',
    `R_UPDATE` INT(11) COMMENT '更新人编号',
    `S_UPDATE` VARCHAR(50) COMMENT '更新人',
    `T_UPDATE` TIMESTAMP NOT NULL COMMENT '更新时间',
    `R_TENANT` INT(11) COMMENT '租户编号',
    `S_TENANT` VARCHAR(300) COMMENT '租户名称',
    `P_TENANT` CHAR(1) COMMENT '租户类型',
    `N_STATE` INT(11) COMMENT '状态',
    `B_DELETE` CHAR(1) COMMENT '删除标志',
    `N_INDEX` INT(11) COMMENT '排序',
    `N_VERSION` INT(11) COMMENT '版本',
  PRIMARY KEY (`UID`)
);

--------------------------------------------------------
-- 达标体系文件归档表
--------------------------------------------------------
DROP TABLE IF EXISTS `SYS_STDTMP_FILE_ARCH`;
CREATE TABLE `SYS_STDTMP_FILE_ARCH` (
    `UID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '内部ID',
    `SID` INT(11) COMMENT '归档前的ID',
    `C_NAME` VARCHAR(300) COMMENT '名称',
    `C_DESC` VARCHAR(2000) COMMENT '描述',
    `R_TEMPLATE` INT(11) COMMENT '所属模板',
    `R_SID` INT(11) COMMENT '所属文件夹SID',
    `S_NAME` VARCHAR(300) COMMENT '所属文件夹名称',
    `B_REMIND` CHAR(1) DEFAULT '1' COMMENT '是否提醒',
    `N_CYCLE` INT(11) COMMENT '更新周期（数量）',
    `P_CYCLE` VARCHAR(32) COMMENT '周期单位SID',
    `S_CYCLE` VARCHAR(100) COMMENT '周期单位名称',
    `C_EXPLAIN` VARCHAR(2000) COMMENT '政策解读',
    `P_TMPFILE` VARCHAR(32) COMMENT '文件类型编码',
    `S_TMPFILE` VARCHAR(100) COMMENT '文件类型名称',
    `R_CREATE` INT(11) COMMENT '创建人编号',
    `S_CREATE` VARCHAR(50) COMMENT '创建人',
    `T_CREATE` DATETIME COMMENT '创建时间',
    `R_UPDATE` INT(11) COMMENT '更新人编号',
    `S_UPDATE` VARCHAR(50) COMMENT '更新人',
    `T_UPDATE` TIMESTAMP NOT NULL COMMENT '更新时间',
    `R_TENANT` INT(11) COMMENT '租户编号',
    `S_TENANT` VARCHAR(300) COMMENT '租户名称',
    `P_TENANT` CHAR(1) COMMENT '租户类型',
    `N_STATE` INT(11) COMMENT '状态',
    `B_DELETE` CHAR(1) COMMENT '删除标志',
    `N_INDEX` INT(11) COMMENT '排序',
    `N_VERSION` INT(11) COMMENT '版本',
  PRIMARY KEY (`UID`)
);

--------------------------------------------------------
-- 模板文件大文本存储归档表
--------------------------------------------------------
DROP TABLE IF EXISTS `SYS_TEMPLATE_TEXT_ARCH`;
CREATE TABLE `SYS_TEMPLATE_TEXT_ARCH` (
    `UID` INT(11) NOT NULL AUTO_INCREMENT,
    `SID` INT(11) NOT NULL COMMENT '原始主键',
    `R_TEMPLATE` INT(11) NOT NULL DEFAULT '0' COMMENT '所属模板',
    `P_TMPFILE` VARCHAR(32) COMMENT '模板类型编号',
    `R_SID` INT(11) COMMENT '对应记录ID',
    `C_CONTENT` LONGTEXT COMMENT '内容',
    `R_CREATE` INT(11) COMMENT '创建人编号',
    `S_CREATE` VARCHAR(50) COMMENT '创建人',
    `T_CREATE` DATETIME COMMENT '创建时间',
    `R_UPDATE` INT(11) COMMENT '更新人编号',
    `S_UPDATE` VARCHAR(50) COMMENT '更新人',
    `T_UPDATE` TIMESTAMP NOT NULL COMMENT '更新时间',
    `R_TENANT` INT(11) COMMENT '租户编号',
    `S_TENANT` VARCHAR(300) COMMENT '租户名称',
    `P_TENANT` CHAR(1) COMMENT '租户类型',
    `N_STATE` INT(11) COMMENT '状态',
    `B_DELETE` CHAR(1) COMMENT '删除标志',
    `N_INDEX` INT(11) COMMENT '排序',
    `N_VERSION` INT(11) COMMENT '版本',
  PRIMARY KEY (`UID`)
);

/**************************************************************************/
DROP TABLE IF EXISTS `SSM_TEMPLATE`;
CREATE TABLE `SSM_TEMPLATE` (
  `SID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `R_TEMPLATE` INT(11) COMMENT '模板编号',
  `P_PROFESSION` INT(11) COMMENT '企业专业编号',
  `R_CREATE` INT(11) COMMENT '创建人编号',
  `S_CREATE` VARCHAR(50) COMMENT '创建人',
  `T_CREATE` DATETIME COMMENT '创建时间',
  `R_UPDATE` INT(11) COMMENT '更新人编号',
  `S_UPDATE` VARCHAR(50) COMMENT '更新人',
  `T_UPDATE` TIMESTAMP NOT NULL COMMENT '更新时间',
  `R_TENANT` INT(11) COMMENT '企业编号',
  `S_TENANT` VARCHAR(300) COMMENT '企业名称',
  `P_TENANT` CHAR(1) COMMENT '租户类型',
  `N_STATE` INT(11) COMMENT '状态',
  `B_DELETE` CHAR(1) COMMENT '删除标志',
  `N_INDEX` INT(11) COMMENT '排序',
  `N_VERSION` INT(11) COMMENT '版本',
  PRIMARY KEY (`SID`)
);

DROP TABLE IF EXISTS `SSM_TEMPLATE_VERSION`;
CREATE TABLE `SSM_TEMPLATE_VERSION` (
  `SID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `R_TEMPLATE` INT(11) COMMENT '模板编号',
  `P_PROFESSION` INT(11) COMMENT '企业专业编号',
  `R_CREATE` INT(11) COMMENT '创建人编号',
  `S_CREATE` VARCHAR(50) COMMENT '创建人',
  `T_CREATE` DATETIME COMMENT '创建时间',
  `R_UPDATE` INT(11) COMMENT '更新人编号',
  `S_UPDATE` VARCHAR(50) COMMENT '更新人',
  `T_UPDATE` TIMESTAMP NOT NULL COMMENT '更新时间',
  `R_TENANT` INT(11) COMMENT '企业编号',
  `S_TENANT` VARCHAR(300) COMMENT '企业名称',
  `P_TENANT` CHAR(1) COMMENT '租户类型',
  `N_STATE` INT(11) COMMENT '状态',
  `B_DELETE` CHAR(1) COMMENT '删除标志',
  `N_INDEX` INT(11) COMMENT '排序',
  `N_VERSION` INT(11) COMMENT '版本',
  PRIMARY KEY (`SID`)
);

DROP TABLE IF EXISTS `SSM_STDTMP_FOLDER`;
CREATE TABLE `SSM_STDTMP_FOLDER` (
  `UID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '内部编号',
  `SID` INT(11) NOT NULL COMMENT '目录ID，直接拷贝自模模板，不做处理直接使用。',
  `R_TENANT` INT(11) COMMENT '租户编号',
  `S_TENANT` VARCHAR(300) COMMENT '租户编号',
  `P_TENANT` CHAR(1) COMMENT '租户编号',
  `R_TEMPLATE` INT(11) COMMENT '所属模板SID',
  `P_PROFESSION` INT(11) COMMENT '所属专业ID',
  `C_NAME` VARCHAR(300) COMMENT '文件夹名称',
  `R_SID` INT(11) DEFAULT '0' COMMENT '父文件夹',
  `N_COUNT` INT(11) DEFAULT '0' COMMENT '记录文件数量',
  `C_DESC` VARCHAR(2000) COMMENT '描述',
  `C_LOGO` VARCHAR(200) COMMENT 'LOGO图',
  `R_CREATE` INT(11) COMMENT '创建人编号',
  `S_CREATE` VARCHAR(50) COMMENT '创建人',
  `T_CREATE` DATETIME COMMENT '创建时间',
  `R_UPDATE` INT(11) COMMENT '更新人编号',
  `S_UPDATE` VARCHAR(50) COMMENT '更新人',
  `T_UPDATE` TIMESTAMP NOT NULL COMMENT '更新时间',
  `N_STATE` INT(11) COMMENT '状态',
  `B_DELETE` CHAR(1) COMMENT '删除标志',
  `N_INDEX` INT(11) COMMENT '排序',
  `N_VERSION` INT(11) COMMENT '版本',
  PRIMARY KEY (`UID`)
);

DROP TABLE IF EXISTS `SSM_STDTMP_FILE`;
CREATE TABLE `SSM_STDTMP_FILE` (
  `UID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '内部编号',
  `SID` INT(11) NOT NULL COMMENT '目录ID，直接拷贝自模模板，不做处理直接使用。',
  `R_TENANT` INT(11) COMMENT '租户编号',
  `S_TENANT` VARCHAR(300) COMMENT '租户编号',
  `P_TENANT` CHAR(1) COMMENT '租户编号',
  `R_TEMPLATE` INT(11) COMMENT '所属模板ID',
  `P_PROFESSION` INT(11) COMMENT '所属专业ID',
  `C_NAME` VARCHAR(300) COMMENT '名称',
  `N_COUNT` INT(11) DEFAULT '0' COMMENT '记录文件数量',
  `C_DESC` VARCHAR(2000) COMMENT '描述',
  `R_SID` INT(11) COMMENT '所属文件夹SID',
  `S_NAME` VARCHAR(300) COMMENT '所属文件夹名称',
  `B_REMIND` CHAR(1) DEFAULT '1' COMMENT '是否提醒',
  `N_CYCLE` INT(11) COMMENT '更新周期（数量）',
  `P_CYCLE` VARCHAR(32) COMMENT '周期单位SID',
  `S_CYCLE` VARCHAR(100) COMMENT '周期单位名称',
  `C_EXPLAIN` VARCHAR(2000) COMMENT '政策解读',
  `P_TMPFILE` VARCHAR(32) COMMENT '文件类型编码',
  `S_TMPFILE` VARCHAR(100) COMMENT '文件类型名称',
  `R_CREATE` INT(11) COMMENT '创建人编号',
  `S_CREATE` VARCHAR(50) COMMENT '创建人',
  `T_CREATE` DATETIME COMMENT '创建时间',
  `R_UPDATE` INT(11) COMMENT '更新人编号',
  `S_UPDATE` VARCHAR(50) COMMENT '更新人',
  `T_UPDATE` TIMESTAMP NOT NULL COMMENT '更新时间',
  `N_STATE` INT(11) COMMENT '状态',
  `B_DELETE` CHAR(1) COMMENT '删除标志',
  `N_INDEX` INT(11) COMMENT '排序',
  `N_VERSION` INT(11) COMMENT '版本',
  PRIMARY KEY (`UID`)
);

DROP TABLE IF EXISTS `SSM_TEMPLATE_TEXT`;
CREATE TABLE `SSM_TEMPLATE_TEXT` (
  `SID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `R_TEMPLATE` INT(11) NOT NULL DEFAULT '0' COMMENT '所属模板',
  `P_PROFESSION` INT(11) COMMENT '企业专业编号',
  `P_TMPFILE` VARCHAR(32) NOT NULL COMMENT '模板文件类型代码',
  `R_SID` INT(11) COMMENT '对应记录ID',
  `C_CONTENT` LONGTEXT COMMENT '内容',
  `R_CREATE` INT(11) COMMENT '创建人编号',
  `S_CREATE` VARCHAR(50) COMMENT '创建人',
  `T_CREATE` DATETIME COMMENT '创建时间',
  `R_UPDATE` INT(11) COMMENT '更新人编号',
  `S_UPDATE` VARCHAR(50) COMMENT '更新人',
  `T_UPDATE` TIMESTAMP NOT NULL COMMENT '更新时间',
  `R_TENANT` INT(11) COMMENT '租户编号',
  `S_TENANT` VARCHAR(300) COMMENT '租户名称',
  `P_TENANT` CHAR(1) COMMENT '租户类型',
  `N_STATE` INT(11) COMMENT '状态',
  `B_DELETE` CHAR(1) COMMENT '删除标志',
  `N_INDEX` INT(11) COMMENT '排序',
  `N_VERSION` INT(11) COMMENT '版本',
  PRIMARY KEY (`SID`)
);

/*************************************************************************/

DROP TABLE IF EXISTS `SSM_STDTMP_FOLDER_ARCH`;
CREATE TABLE `SSM_STDTMP_FOLDER_ARCH` (
  `UID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '归档用主键',
  `N_ARCH_VERSION` INT(11) NOT NULL DEFAULT '0' COMMENT '归档版本',
  `SID` INT(11) COMMENT '自增主键',
  `R_TENANT` INT(11) COMMENT '租户编号',
  `S_TENANT` VARCHAR(300) COMMENT '租户编号',
  `P_TENANT` CHAR(1) COMMENT '租户编号',
  `R_TEMPLATE` INT(11) COMMENT '所属模板SID',
  `P_PROFESSION` INT(11) COMMENT '所属专业ID',
  `C_NAME` VARCHAR(300) COMMENT '文件夹名称',
  `R_SID` INT(11) DEFAULT '0' COMMENT '父文件夹',
  `R_SOURCE` INT(11) COMMENT '来源SID，记录复制自哪条记录。',
  `N_COUNT` INT(11) DEFAULT '0' COMMENT '记录文件数量',
  `C_DESC` VARCHAR(2000) COMMENT '描述',
  `C_LOGO` VARCHAR(200) COMMENT 'LOGO图',
  `R_CREATE` INT(11) COMMENT '创建人编号',
  `S_CREATE` VARCHAR(50) COMMENT '创建人',
  `T_CREATE` DATETIME COMMENT '创建时间',
  `R_UPDATE` INT(11) COMMENT '更新人编号',
  `S_UPDATE` VARCHAR(50) COMMENT '更新人',
  `T_UPDATE` TIMESTAMP NOT NULL COMMENT '更新时间',
  `N_STATE` INT(11) COMMENT '状态',
  `B_DELETE` CHAR(1) COMMENT '删除标志',
  `N_INDEX` INT(11) COMMENT '排序',
  `N_VERSION` INT(11) COMMENT '版本',
  PRIMARY KEY (`UID`)
);

DROP TABLE IF EXISTS `SSM_STDTMP_FILE_ARCH`;
CREATE TABLE `SSM_STDTMP_FILE_ARCH` (
  `UID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '归档用主键',
  `N_ARCH_VERSION` INT(11) NOT NULL DEFAULT '0' COMMENT '归档版本',
  `SID` INT(11) COMMENT '自增主键',
  `R_TENANT` INT(11) COMMENT '租户编号',
  `S_TENANT` VARCHAR(300) COMMENT '租户编号',
  `P_TENANT` CHAR(1) COMMENT '租户编号',
  `R_TEMPLATE` INT(11) COMMENT '所属模板ID',
  `P_PROFESSION` INT(11) COMMENT '所属专业ID',
  `C_NAME` VARCHAR(300) COMMENT '名称',
  `R_SOURCE` INT(11) COMMENT '来源SID，记录复制自哪条记录。',
  `N_COUNT` INT(11) DEFAULT '0' COMMENT '记录文件数量',
  `C_DESC` VARCHAR(2000) COMMENT '描述',
  `R_SID` INT(11) COMMENT '所属文件夹SID',
  `S_NAME` VARCHAR(300) COMMENT '所属文件夹名称',
  `B_REMIND` CHAR(1) DEFAULT '1' COMMENT '是否提醒',
  `N_CYCLE` INT(11) COMMENT '更新周期（数量）',
  `P_CYCLE` VARCHAR(32) COMMENT '周期单位SID',
  `S_CYCLE` VARCHAR(100) COMMENT '周期单位名称',
  `C_EXPLAIN` VARCHAR(2000) COMMENT '政策解读',
  `P_TMPFILE` VARCHAR(32) COMMENT '文件类型编码',
  `S_TMPFILE` VARCHAR(100) COMMENT '文件类型名称',
  `R_CREATE` INT(11) COMMENT '创建人编号',
  `S_CREATE` VARCHAR(50) COMMENT '创建人',
  `T_CREATE` DATETIME COMMENT '创建时间',
  `R_UPDATE` INT(11) COMMENT '更新人编号',
  `S_UPDATE` VARCHAR(50) COMMENT '更新人',
  `T_UPDATE` TIMESTAMP NOT NULL COMMENT '更新时间',
  `N_STATE` INT(11) COMMENT '状态',
  `B_DELETE` CHAR(1) COMMENT '删除标志',
  `N_INDEX` INT(11) COMMENT '排序',
  `N_VERSION` INT(11) COMMENT '版本',
  PRIMARY KEY (`UID`)
);

DROP TABLE IF EXISTS `SSM_TEMPLATE_TEXT_ARCH`;
CREATE TABLE `SSM_TEMPLATE_TEXT_ARCH` (
  `UID` INT(11) NOT NULL AUTO_INCREMENT,
  `SID` INT(11) NOT NULL COMMENT '原始主键',
  `R_TEMPLATE` INT(11) NOT NULL DEFAULT '0' COMMENT '所属模板',
  `P_PROFESSION` INT(11) COMMENT '企业专业编号',
  `P_TMPFILE` VARCHAR(32) COMMENT '模板类型编号',
  `R_SID` INT(11) COMMENT '对应记录ID',
  `C_CONTENT` LONGTEXT COMMENT '内容',
  `R_CREATE` INT(11) COMMENT '创建人编号',
  `S_CREATE` VARCHAR(50) COMMENT '创建人',
  `T_CREATE` DATETIME COMMENT '创建时间',
  `R_UPDATE` INT(11) COMMENT '更新人编号',
  `S_UPDATE` VARCHAR(50) COMMENT '更新人',
  `T_UPDATE` TIMESTAMP NOT NULL COMMENT '更新时间',
  `R_TENANT` INT(11) COMMENT '租户编号',
  `S_TENANT` VARCHAR(300) COMMENT '租户名称',
  `P_TENANT` CHAR(1) COMMENT '租户类型',
  `N_STATE` INT(11) COMMENT '状态',
  `B_DELETE` CHAR(1) COMMENT '删除标志',
  `N_INDEX` INT(11) COMMENT '排序',
  `N_VERSION` INT(11) COMMENT '版本',
  PRIMARY KEY (`UID`)
);
