--评审端通知公告
DROP TABLE IF EXISTS SYS_REVIEW_NOTICE;
CREATE TABLE SYS_REVIEW_NOTICE
(
  `SID`       INT(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `C_TITLE`   VARCHAR(300) COMMENT '标题',
  `C_CONTENT` TEXT COMMENT '内容',
  `R_PUBLISH`  INT(11) COMMENT '发布人SID',
  `S_PUBLISH`  VARCHAR(300) COMMENT '发布人名称',
  `T_PUBLISH`  DATETIME COMMENT '发布时间',
  `R_RECEIVER`   INT(11) COMMENT '接收者编号',
  `P_PROFESSION` INT(11) COMMENT '所属专业ID',
  `B_READER`  CHAR(1) COMMENT '阅读状态',
  `R_CREATE`  INT(11) COMMENT '创建人编号',
  `S_CREATE`  VARCHAR(50) COMMENT '创建人',
  `T_CREATE`  DATETIME COMMENT '创建时间',
  `R_UPDATE`  INT(11) COMMENT '更新人编号',
  `S_UPDATE`  VARCHAR(50) COMMENT '更新人',
  `T_UPDATE`  TIMESTAMP COMMENT '更新时间',
  `R_TENANT`  INT(11) COMMENT '租户编号',
  `S_TENANT`  VARCHAR(300) COMMENT '租户名称',
  `P_TENANT`  CHAR(1) COMMENT '租户类型',
  `N_STATE`   CHAR(1) COMMENT '发布状态,1表示已发布,0表示未发布',
  `N_INDEX`   INT COMMENT '排序',
  `N_VERSION` INT COMMENT '版本',
  PRIMARY KEY (`SID`)
);