-- 系统大文本表:
DROP TABLE IF EXISTS SYS_ATTACH_TEXT;
CREATE TABLE SYS_ATTACH_TEXT
(
  `SID`       INT(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `R_TABLE`   VARCHAR(32) COMMENT '对应表',
  `R_SID`     INT(11) COMMENT '对应记录编号',
  `R_FIELD`   VARCHAR(32) COMMENT '对应字段',
  `C_CONTENT` TEXT COMMENT '内容',
  `R_CREATE`  INT(11) COMMENT '创建人编号',
  `S_CREATE`  VARCHAR(50) COMMENT '创建人',
  `T_CREATE`  DATETIME COMMENT '创建时间',
  `R_UPDATE`  INT(11) COMMENT '更新人编号',
  `S_UPDATE`  VARCHAR(50) COMMENT '更新人',
  `T_UPDATE`  TIMESTAMP COMMENT '更新时间',
  `R_TENANT`  INT(11) COMMENT '租户编号',
  `S_TENANT`  VARCHAR(300) COMMENT '租户名称',
  `P_TENANT`  CHAR(1) COMMENT '租户类型',
  `N_STATE`   INT COMMENT '状态',
  `B_DELETE`  CHAR(1) COMMENT '删除标志',
  `N_INDEX`   INT COMMENT '排序',
  `N_VERSION` INT COMMENT '版本',
  PRIMARY KEY (`SID`)
);
-- 系统附件:
DROP TABLE IF EXISTS SYS_ATTACH_FILE;
CREATE TABLE SYS_ATTACH_FILE
(
  `SID`          INT(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `R_TABLE`      VARCHAR(32) COMMENT '对应表',
  `R_SID`        INT(11) COMMENT '对应记录编号',
  `C_INNER_NAME` VARCHAR(200) COMMENT '内部文件名',
  `C_OUTER_NAME` VARCHAR(200) COMMENT '外部文件名',
  `C_EXT`        VARCHAR(50) COMMENT '扩展名',
  `N_LENGTH`     INT(11) COMMENT '文件大小',
  `C_PATH`       VARCHAR(200) COMMENT '物理路径，使用相对定位表示目录。',
  `P_SERVER`     VARCHAR(200) COMMENT '存放附件的服务器名称',
  `R_CREATE`     INT(11) COMMENT '创建人编号',
  `S_CREATE`     VARCHAR(50) COMMENT '创建人',
  `T_CREATE`     DATETIME COMMENT '创建时间',
  `R_UPDATE`     INT(11) COMMENT '更新人编号',
  `S_UPDATE`     VARCHAR(50) COMMENT '更新人',
  `T_UPDATE`     TIMESTAMP COMMENT '更新时间',
  `R_TENANT`     INT(11) COMMENT '租户编号',
  `S_TENANT`     VARCHAR(300) COMMENT '租户名称',
  `P_TENANT`     CHAR(1) COMMENT '租户类型',
  `N_STATE`      INT COMMENT '状态',
  `B_DELETE`     CHAR(1) COMMENT '删除标志',
  `N_INDEX`      INT COMMENT '排序',
  `N_VERSION`    INT COMMENT '版本',
  PRIMARY KEY (`SID`)
);
-- 模板管理:
DROP TABLE IF EXISTS SYS_TEMPLATE;
CREATE TABLE SYS_TEMPLATE
(
  `SID`       INT(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `C_NAME`    VARCHAR(300) COMMENT '模板名称',
  `R_CREATE`  INT(11) COMMENT '创建人编号',
  `S_CREATE`  VARCHAR(50) COMMENT '创建人',
  `T_CREATE`  DATETIME COMMENT '创建时间',
  `R_UPDATE`  INT(11) COMMENT '更新人编号',
  `S_UPDATE`  VARCHAR(50) COMMENT '更新人',
  `T_UPDATE`  TIMESTAMP COMMENT '更新时间',
  `R_TENANT`  INT(11) COMMENT '租户编号',
  `S_TENANT`  VARCHAR(300) COMMENT '租户名称',
  `P_TENANT`  CHAR(1) COMMENT '租户类型',
  `N_STATE`   INT COMMENT '状态',
  `B_DELETE`  CHAR(1) COMMENT '删除标志',
  `N_INDEX`   INT COMMENT '排序',
  `N_VERSION` INT COMMENT '版本',
  PRIMARY KEY (`SID`)
);
-- 达标体系模板文件夹:
DROP TABLE IF EXISTS SYS_STDTMP_FOLDER;
CREATE TABLE SYS_STDTMP_FOLDER
(
  `SID`          INT(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `C_NAME`       VARCHAR(300) COMMENT '文件夹名称',
  `R_TEMPLATE`   INT(11) COMMENT '所属模板SID',
  `R_SID`        INT(11)          DEFAULT 0 COMMENT '父文件夹',
  `C_DESC`       VARCHAR(2000) COMMENT '描述',
  `C_LOGO`       VARCHAR(200) COMMENT 'LOGO图',
  `R_CREATE`     INT(11) COMMENT '创建人编号',
  `S_CREATE`     VARCHAR(50) COMMENT '创建人',
  `T_CREATE`     DATETIME COMMENT '创建时间',
  `R_UPDATE`     INT(11) COMMENT '更新人编号',
  `S_UPDATE`     VARCHAR(50) COMMENT '更新人',
  `T_UPDATE`     TIMESTAMP COMMENT '更新时间',
  `R_TENANT`     INT(11) COMMENT '租户编号',
  `S_TENANT`     VARCHAR(300) COMMENT '租户名称',
  `P_TENANT`     CHAR(1) COMMENT '租户类型',
  `N_STATE`      INT COMMENT '状态',
  `B_DELETE`     CHAR(1) COMMENT '删除标志',
  `N_INDEX`      INT COMMENT '排序',
  `N_VERSION`    INT COMMENT '版本',
  PRIMARY KEY (`SID`)
);
-- 达标体系模板文件:
DROP TABLE IF EXISTS SYS_STDTMP_FILE;
CREATE TABLE SYS_STDTMP_FILE
(
  `SID`       INT(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `C_NAME`    VARCHAR(300) COMMENT '名称',
  `C_DESC`    VARCHAR(2000) COMMENT '描述',
  `R_SID`     INT(11) COMMENT '所属文件夹SID',
  `S_NAME`    VARCHAR(300) COMMENT '所属文件夹名称',
  `B_REMIND`  CHAR(1)          DEFAULT 1 COMMENT '是否提醒',
  `N_CYCLE`   INT COMMENT '更新周期（数量）',
  `P_CYCLE`   VARCHAR(32) COMMENT '周期单位SID',
  `S_CYCLE`   VARCHAR(100) COMMENT '周期单位名称',
  `C_EXPLAIN` VARCHAR(2000) COMMENT '政策解读',
  `P_TMPFILE` VARCHAR(32) COMMENT '文件类型SID',
  `S_TMPFILE` VARCHAR(100) COMMENT '文件类型名称',
  `R_TMPFILE` INT(11) COMMENT '模板文件SID',
  `R_CREATE`  INT(11) COMMENT '创建人编号',
  `S_CREATE`  VARCHAR(50) COMMENT '创建人',
  `T_CREATE`  DATETIME COMMENT '创建时间',
  `R_UPDATE`  INT(11) COMMENT '更新人编号',
  `S_UPDATE`  VARCHAR(50) COMMENT '更新人',
  `T_UPDATE`  TIMESTAMP COMMENT '更新时间',
  `R_TENANT`  INT(11) COMMENT '租户编号',
  `S_TENANT`  VARCHAR(300) COMMENT '租户名称',
  `P_TENANT`  CHAR(1) COMMENT '租户类型',
  `N_STATE`   INT COMMENT '状态',
  `B_DELETE`  CHAR(1) COMMENT '删除标志',
  `N_INDEX`   INT COMMENT '排序',
  `N_VERSION` INT COMMENT '版本',
  PRIMARY KEY (`SID`)
);
-- 达标体系制度文件模板配置:
DROP TABLE IF EXISTS SYS_STDTMP_FILE_01;
CREATE TABLE SYS_STDTMP_FILE_01
(
  `SID`       INT(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `C_NAME`    VARCHAR(300) COMMENT '名称',
  `B_CONTROL` CHAR(1)          DEFAULT 0 COMMENT '是否受控',
  `C_NUMBER`  VARCHAR(32) COMMENT '文件编号',
  `C_DEPT_01` VARCHAR(200) COMMENT '执行部门',
  `C_DEPT_02` VARCHAR(200) COMMENT '监督部门',
  `T_DATE_01` DATE COMMENT '编制日期',
  `T_DATE_02` DATE COMMENT '审核日期',
  `T_DATE_03` DATE COMMENT '批准日期',
  `P_SATUS`   VARCHAR(32) COMMENT '文件状态编码',
  `S_SATUS`   VARCHAR(100) COMMENT '文件状态名称',
  `N_TIMES`   INT              DEFAULT 0 COMMENT '修订次数',
  `R_CREATE`  INT(11) COMMENT '创建人编号',
  `S_CREATE`  VARCHAR(50) COMMENT '创建人',
  `T_CREATE`  DATETIME COMMENT '创建时间',
  `R_UPDATE`  INT(11) COMMENT '更新人编号',
  `S_UPDATE`  VARCHAR(50) COMMENT '更新人',
  `T_UPDATE`  TIMESTAMP COMMENT '更新时间',
  `R_TENANT`  INT(11) COMMENT '租户编号',
  `S_TENANT`  VARCHAR(300) COMMENT '租户名称',
  `P_TENANT`  CHAR(1) COMMENT '租户类型',
  `N_STATE`   INT COMMENT '状态',
  `B_DELETE`  CHAR(1) COMMENT '删除标志',
  `N_INDEX`   INT COMMENT '排序',
  `N_VERSION` INT COMMENT '版本',
  PRIMARY KEY (`SID`)
);
-- 达标体系通知文件模板配置:
DROP TABLE IF EXISTS SYS_STDTMP_FILE_02;
CREATE TABLE SYS_STDTMP_FILE_02
(
  `SID`       INT(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `C_NAME`    VARCHAR(300) COMMENT '名称',
  `C_NUMBER`  VARCHAR(32) COMMENT '文件编号',
  `C_DEPT_01` VARCHAR(500) COMMENT '发布部门',
  `C_DEPT_02` VARCHAR(500) COMMENT '主送部门',
  `C_DEPT_03` VARCHAR(500) COMMENT '抄送部门',
  `T_DATE_01` DATE COMMENT '发布日期',
  `P_SATUS`   VARCHAR(32) COMMENT '文件状态编码',
  `S_SATUS`   VARCHAR(100) COMMENT '文件状态名称',
  `N_TIMES`   INT              DEFAULT 0 COMMENT '修订次数',
  `R_CREATE`  INT(11) COMMENT '创建人编号',
  `S_CREATE`  VARCHAR(50) COMMENT '创建人',
  `T_CREATE`  DATETIME COMMENT '创建时间',
  `R_UPDATE`  INT(11) COMMENT '更新人编号',
  `S_UPDATE`  VARCHAR(50) COMMENT '更新人',
  `T_UPDATE`  TIMESTAMP COMMENT '更新时间',
  `R_TENANT`  INT(11) COMMENT '租户编号',
  `S_TENANT`  VARCHAR(300) COMMENT '租户名称',
  `P_TENANT`  CHAR(1) COMMENT '租户类型',
  `N_STATE`   INT COMMENT '状态',
  `B_DELETE`  CHAR(1) COMMENT '删除标志',
  `N_INDEX`   INT COMMENT '排序',
  `N_VERSION` INT COMMENT '版本',
  PRIMARY KEY (`SID`)
);
-- 达标体系执行文件模板配置:
DROP TABLE IF EXISTS SYS_STDTMP_FILE_03;
CREATE TABLE SYS_STDTMP_FILE_03
(
  `SID`       INT(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `C_NAME`    VARCHAR(300) COMMENT '名称',
  `R_CREATE`  INT(11) COMMENT '创建人编号',
  `S_CREATE`  VARCHAR(50) COMMENT '创建人',
  `T_CREATE`  DATETIME COMMENT '创建时间',
  `R_UPDATE`  INT(11) COMMENT '更新人编号',
  `S_UPDATE`  VARCHAR(50) COMMENT '更新人',
  `T_UPDATE`  TIMESTAMP COMMENT '更新时间',
  `R_TENANT`  INT(11) COMMENT '租户编号',
  `S_TENANT`  VARCHAR(300) COMMENT '租户名称',
  `P_TENANT`  CHAR(1) COMMENT '租户类型',
  `N_STATE`   INT COMMENT '状态',
  `B_DELETE`  CHAR(1) COMMENT '删除标志',
  `N_INDEX`   INT COMMENT '排序',
  `N_VERSION` INT COMMENT '版本',
  PRIMARY KEY (`SID`)
);
-- 达标体系培训执行文件模板配置:
DROP TABLE IF EXISTS SYS_STDTMP_FILE_04;
CREATE TABLE SYS_STDTMP_FILE_04
(
  `SID`       INT(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `C_NAME`    VARCHAR(300) COMMENT '名称',
  `T_TIME`    DATE COMMENT '培训日期',
  `C_USER_01` VARCHAR(300) COMMENT '教育人',
  `C_ADDR`    VARCHAR(200) COMMENT '培训地点',
  `P_TYPE`    VARCHAR(32) COMMENT '培训种类',
  `S_TYPE`    VARCHAR(100) COMMENT '培训种类',
  `N_TIME`    INT COMMENT '学时',
  `C_USER_02` VARCHAR(300) COMMENT '记录人',
  `R_CREATE`  INT(11) COMMENT '创建人编号',
  `S_CREATE`  VARCHAR(50) COMMENT '创建人',
  `T_CREATE`  DATETIME COMMENT '创建时间',
  `R_UPDATE`  INT(11) COMMENT '更新人编号',
  `S_UPDATE`  VARCHAR(50) COMMENT '更新人',
  `T_UPDATE`  TIMESTAMP COMMENT '更新时间',
  `R_TENANT`  INT(11) COMMENT '租户编号',
  `S_TENANT`  VARCHAR(300) COMMENT '租户名称',
  `P_TENANT`  CHAR(1) COMMENT '租户类型',
  `N_STATE`   INT COMMENT '状态',
  `B_DELETE`  CHAR(1) COMMENT '删除标志',
  `N_INDEX`   INT COMMENT '排序',
  `N_VERSION` INT COMMENT '版本',
  PRIMARY KEY (`SID`)
);
-- 达标体系培训文件模板配置:
DROP TABLE IF EXISTS SYS_STDTMP_FILE_05;
CREATE TABLE SYS_STDTMP_FILE_05
(
  `SID`       INT(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `C_NAME`    VARCHAR(300) COMMENT '名称',
  `R_CREATE`  INT(11) COMMENT '创建人编号',
  `S_CREATE`  VARCHAR(50) COMMENT '创建人',
  `T_CREATE`  DATETIME COMMENT '创建时间',
  `R_UPDATE`  INT(11) COMMENT '更新人编号',
  `S_UPDATE`  VARCHAR(50) COMMENT '更新人',
  `T_UPDATE`  TIMESTAMP COMMENT '更新时间',
  `R_TENANT`  INT(11) COMMENT '租户编号',
  `S_TENANT`  VARCHAR(300) COMMENT '租户名称',
  `P_TENANT`  CHAR(1) COMMENT '租户类型',
  `N_STATE`   INT COMMENT '状态',
  `B_DELETE`  CHAR(1) COMMENT '删除标志',
  `N_INDEX`   INT COMMENT '排序',
  `N_VERSION` INT COMMENT '版本',
  PRIMARY KEY (`SID`)
);







-- 达标体系模板文件夹:
DROP TABLE IF EXISTS SSM_STDTMP_FOLDER;
CREATE TABLE SSM_STDTMP_FOLDER
(
  `SID`          INT(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `C_NAME`       VARCHAR(300) COMMENT '文件夹名称',
  `R_TEMPLATE`   INT(11) COMMENT '所属模板SID',
  `R_SID`        INT(11)          DEFAULT 0 COMMENT '父文件夹',
  `C_DESC`       VARCHAR(2000) COMMENT '描述',
  `C_LOGO`       VARCHAR(200) COMMENT 'LOGO图',
  `R_CREATE`     INT(11) COMMENT '创建人编号',
  `S_CREATE`     VARCHAR(50) COMMENT '创建人',
  `T_CREATE`     DATETIME COMMENT '创建时间',
  `R_UPDATE`     INT(11) COMMENT '更新人编号',
  `S_UPDATE`     VARCHAR(50) COMMENT '更新人',
  `T_UPDATE`     TIMESTAMP COMMENT '更新时间',
  `R_TENANT`     INT(11) COMMENT '租户编号',
  `S_TENANT`     VARCHAR(300) COMMENT '租户名称',
  `P_TENANT`     CHAR(1) COMMENT '租户类型',
  `N_STATE`      INT COMMENT '状态',
  `B_DELETE`     CHAR(1) COMMENT '删除标志',
  `N_INDEX`      INT COMMENT '排序',
  `N_VERSION`    INT COMMENT '版本',
  PRIMARY KEY (`SID`)
);
-- 达标体系模板文件:
DROP TABLE IF EXISTS SSM_STDTMP_FILE;
CREATE TABLE SSM_STDTMP_FILE
(
  `SID`       INT(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `C_NAME`    VARCHAR(300) COMMENT '名称',
  `C_DESC`    VARCHAR(2000) COMMENT '描述',
  `R_SID`     INT(11) COMMENT '所属文件夹SID',
  `S_NAME`    VARCHAR(300) COMMENT '所属文件夹名称',
  `B_REMIND`  CHAR(1)          DEFAULT 1 COMMENT '是否提醒',
  `N_CYCLE`   INT COMMENT '更新周期（数量）',
  `P_CYCLE`   VARCHAR(32) COMMENT '周期单位SID',
  `S_CYCLE`   VARCHAR(100) COMMENT '周期单位名称',
  `C_EXPLAIN` VARCHAR(2000) COMMENT '政策解读',
  `P_TMPFILE` VARCHAR(32) COMMENT '文件类型SID',
  `S_TMPFILE` VARCHAR(100) COMMENT '文件类型名称',
  `R_TMPFILE` INT(11) COMMENT '模板文件SID',
  `R_CREATE`  INT(11) COMMENT '创建人编号',
  `S_CREATE`  VARCHAR(50) COMMENT '创建人',
  `T_CREATE`  DATETIME COMMENT '创建时间',
  `R_UPDATE`  INT(11) COMMENT '更新人编号',
  `S_UPDATE`  VARCHAR(50) COMMENT '更新人',
  `T_UPDATE`  TIMESTAMP COMMENT '更新时间',
  `R_TENANT`  INT(11) COMMENT '租户编号',
  `S_TENANT`  VARCHAR(300) COMMENT '租户名称',
  `P_TENANT`  CHAR(1) COMMENT '租户类型',
  `N_STATE`   INT COMMENT '状态',
  `B_DELETE`  CHAR(1) COMMENT '删除标志',
  `N_INDEX`   INT COMMENT '排序',
  `N_VERSION` INT COMMENT '版本',
  PRIMARY KEY (`SID`)
);
-- 达标体系制度文件模板配置:
DROP TABLE IF EXISTS SSM_STDTMP_FILE_01;
CREATE TABLE SSM_STDTMP_FILE_01
(
  `SID`       INT(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `C_NAME`    VARCHAR(300) COMMENT '名称',
  `B_CONTROL` CHAR(1)          DEFAULT 0 COMMENT '是否受控',
  `C_NUMBER`  VARCHAR(32) COMMENT '文件编号',
  `C_DEPT_01` VARCHAR(200) COMMENT '执行部门',
  `C_DEPT_02` VARCHAR(200) COMMENT '监督部门',
  `T_DATE_01` DATE COMMENT '编制日期',
  `T_DATE_02` DATE COMMENT '审核日期',
  `T_DATE_03` DATE COMMENT '批准日期',
  `P_SATUS`   VARCHAR(32) COMMENT '文件状态编码',
  `S_SATUS`   VARCHAR(100) COMMENT '文件状态名称',
  `N_TIMES`   INT              DEFAULT 0 COMMENT '修订次数',
  `R_CREATE`  INT(11) COMMENT '创建人编号',
  `S_CREATE`  VARCHAR(50) COMMENT '创建人',
  `T_CREATE`  DATETIME COMMENT '创建时间',
  `R_UPDATE`  INT(11) COMMENT '更新人编号',
  `S_UPDATE`  VARCHAR(50) COMMENT '更新人',
  `T_UPDATE`  TIMESTAMP COMMENT '更新时间',
  `R_TENANT`  INT(11) COMMENT '租户编号',
  `S_TENANT`  VARCHAR(300) COMMENT '租户名称',
  `P_TENANT`  CHAR(1) COMMENT '租户类型',
  `N_STATE`   INT COMMENT '状态',
  `B_DELETE`  CHAR(1) COMMENT '删除标志',
  `N_INDEX`   INT COMMENT '排序',
  `N_VERSION` INT COMMENT '版本',
  PRIMARY KEY (`SID`)
);
-- 达标体系通知文件模板配置:
DROP TABLE IF EXISTS SSM_STDTMP_FILE_02;
CREATE TABLE SSM_STDTMP_FILE_02
(
  `SID`       INT(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `C_NAME`    VARCHAR(300) COMMENT '名称',
  `C_NUMBER`  VARCHAR(32) COMMENT '文件编号',
  `C_DEPT_01` VARCHAR(500) COMMENT '发布部门',
  `C_DEPT_02` VARCHAR(500) COMMENT '主送部门',
  `C_DEPT_03` VARCHAR(500) COMMENT '抄送部门',
  `T_DATE_01` DATE COMMENT '发布日期',
  `P_SATUS`   VARCHAR(32) COMMENT '文件状态编码',
  `S_SATUS`   VARCHAR(100) COMMENT '文件状态名称',
  `N_TIMES`   INT              DEFAULT 0 COMMENT '修订次数',
  `R_CREATE`  INT(11) COMMENT '创建人编号',
  `S_CREATE`  VARCHAR(50) COMMENT '创建人',
  `T_CREATE`  DATETIME COMMENT '创建时间',
  `R_UPDATE`  INT(11) COMMENT '更新人编号',
  `S_UPDATE`  VARCHAR(50) COMMENT '更新人',
  `T_UPDATE`  TIMESTAMP COMMENT '更新时间',
  `R_TENANT`  INT(11) COMMENT '租户编号',
  `S_TENANT`  VARCHAR(300) COMMENT '租户名称',
  `P_TENANT`  CHAR(1) COMMENT '租户类型',
  `N_STATE`   INT COMMENT '状态',
  `B_DELETE`  CHAR(1) COMMENT '删除标志',
  `N_INDEX`   INT COMMENT '排序',
  `N_VERSION` INT COMMENT '版本',
  PRIMARY KEY (`SID`)
);
-- 达标体系执行文件模板配置:
DROP TABLE IF EXISTS SSM_STDTMP_FILE_03;
CREATE TABLE SSM_STDTMP_FILE_03
(
  `SID`       INT(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `C_NAME`    VARCHAR(300) COMMENT '名称',
  `R_CREATE`  INT(11) COMMENT '创建人编号',
  `S_CREATE`  VARCHAR(50) COMMENT '创建人',
  `T_CREATE`  DATETIME COMMENT '创建时间',
  `R_UPDATE`  INT(11) COMMENT '更新人编号',
  `S_UPDATE`  VARCHAR(50) COMMENT '更新人',
  `T_UPDATE`  TIMESTAMP COMMENT '更新时间',
  `R_TENANT`  INT(11) COMMENT '租户编号',
  `S_TENANT`  VARCHAR(300) COMMENT '租户名称',
  `P_TENANT`  CHAR(1) COMMENT '租户类型',
  `N_STATE`   INT COMMENT '状态',
  `B_DELETE`  CHAR(1) COMMENT '删除标志',
  `N_INDEX`   INT COMMENT '排序',
  `N_VERSION` INT COMMENT '版本',
  PRIMARY KEY (`SID`)
);
-- 达标体系培训执行文件模板配置:
DROP TABLE IF EXISTS SSM_STDTMP_FILE_04;
CREATE TABLE SSM_STDTMP_FILE_04
(
  `SID`       INT(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `C_NAME`    VARCHAR(300) COMMENT '名称',
  `T_TIME`    DATE COMMENT '培训日期',
  `C_USER_01` VARCHAR(300) COMMENT '教育人',
  `C_ADDR`    VARCHAR(200) COMMENT '培训地点',
  `P_TYPE`    VARCHAR(32) COMMENT '培训种类',
  `S_TYPE`    VARCHAR(100) COMMENT '培训种类',
  `N_TIME`    INT COMMENT '学时',
  `C_USER_02` VARCHAR(300) COMMENT '记录人',
  `R_CREATE`  INT(11) COMMENT '创建人编号',
  `S_CREATE`  VARCHAR(50) COMMENT '创建人',
  `T_CREATE`  DATETIME COMMENT '创建时间',
  `R_UPDATE`  INT(11) COMMENT '更新人编号',
  `S_UPDATE`  VARCHAR(50) COMMENT '更新人',
  `T_UPDATE`  TIMESTAMP COMMENT '更新时间',
  `R_TENANT`  INT(11) COMMENT '租户编号',
  `S_TENANT`  VARCHAR(300) COMMENT '租户名称',
  `P_TENANT`  CHAR(1) COMMENT '租户类型',
  `N_STATE`   INT COMMENT '状态',
  `B_DELETE`  CHAR(1) COMMENT '删除标志',
  `N_INDEX`   INT COMMENT '排序',
  `N_VERSION` INT COMMENT '版本',
  PRIMARY KEY (`SID`)
);
-- 达标体系培训文件模板配置:
DROP TABLE IF EXISTS SSM_STDTMP_FILE_05;
CREATE TABLE SSM_STDTMP_FILE_05
(
  `SID`       INT(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `C_NAME`    VARCHAR(300) COMMENT '名称',
  `R_CREATE`  INT(11) COMMENT '创建人编号',
  `S_CREATE`  VARCHAR(50) COMMENT '创建人',
  `T_CREATE`  DATETIME COMMENT '创建时间',
  `R_UPDATE`  INT(11) COMMENT '更新人编号',
  `S_UPDATE`  VARCHAR(50) COMMENT '更新人',
  `T_UPDATE`  TIMESTAMP COMMENT '更新时间',
  `R_TENANT`  INT(11) COMMENT '租户编号',
  `S_TENANT`  VARCHAR(300) COMMENT '租户名称',
  `P_TENANT`  CHAR(1) COMMENT '租户类型',
  `N_STATE`   INT COMMENT '状态',
  `B_DELETE`  CHAR(1) COMMENT '删除标志',
  `N_INDEX`   INT COMMENT '排序',
  `N_VERSION` INT COMMENT '版本',
  PRIMARY KEY (`SID`)
);
