/*评审分汇总——空项分*/
CREATE OR REPLACE VIEW V_REVIEW_SUM_BLANK AS
SELECT R_SID,C_PROJECT,SUM(IFNULL(N_SCORE_REVIEW,0))  N
FROM SSM_REVIEW_CONTENT
WHERE C_PROJECT<>'总计' AND C_PROJECT<>'小计'
GROUP BY R_SID,C_PROJECT;

/*评审分汇总——企业实际得分*/
CREATE OR REPLACE VIEW V_REVIEW_SUM_REAL_E AS
SELECT R_SID,C_PROJECT,SUM(IFNULL(N_SCORE_REAL,0))  N
FROM SSM_REVIEW_CONTENT
WHERE C_PROJECT<>'总计' AND C_PROJECT<>'小计'
GROUP BY R_SID,C_PROJECT;

/*评审分汇总——评审实际得分*/
CREATE OR REPLACE VIEW V_REVIEW_SUM_REAL_R AS
SELECT R_SID,C_PROJECT,SUM(IFNULL(N_SCORE_REVIEW,0))  N
FROM SSM_REVIEW_CONTENT
WHERE C_PROJECT<>'总计' AND C_PROJECT<>'小计'
GROUP BY R_SID,C_PROJECT;

/*评审分汇总——数据*/
CREATE OR REPLACE VIEW V_REVIEW_SUM_DATA AS
SELECT T1.R_SID, T1.C_PROJECT,T1.N_INDEX
,SUM(IFNULL(T1.N_SCORE,0)) N_SUBTOTAL /*项目标准分值小计*/
,IFNULL(T2.N,0) N_BLANK/*空项分*/
,IFNULL(T3.N,0) N_REAL /*企业自评得分*/
,IFNULL(T4.N,0) N_REVIEW /*评审得分*/
,SUM(IFNULL(T1.N_SCORE,0)) -IFNULL(T2.N,0) N_GET/*应得分*/
FROM SSM_REVIEW_CONTENT T1
/*空项分*/
LEFT JOIN V_REVIEW_SUM_BLANK T2
	ON T1.R_SID = T2.R_SID AND T1.C_PROJECT=T2.C_PROJECT
/*企业自评得分*/
LEFT JOIN  V_REVIEW_SUM_REAL_E T3
		ON T1.R_SID = T3.R_SID AND T1.C_PROJECT=T3.C_PROJECT
/*评审得分*/
LEFT JOIN  V_REVIEW_SUM_REAL_R T4
		ON T1.R_SID = T4.R_SID AND T1.C_PROJECT=T4.C_PROJECT

WHERE T1.C_PROJECT<>'总计' AND T1.C_PROJECT<>'小计'
GROUP BY T1.R_SID,T1.C_PROJECT
ORDER BY N_INDEX;

/*评审分汇总——小计*/
CREATE OR REPLACE VIEW V_REVIEW_SUM_SUBTOTAL AS
SELECT T1.R_SID
	,SUM(IFNULL(T1.N_SUBTOTAL,0)) N_SUBTOTAL /*项目标准分值小计*/
	,SUM(IFNULL(T1.N_BLANK,0)) N_BLANK/*空项分小计*/
	,SUM(IFNULL(T1.N_REAL,0)) N_REAL /*实际得分小计*/
	,SUM(IFNULL(T1.N_GET,0))  N_GET /*应得分小计*/
	,SUM(IFNULL(T1.N_REVIEW,0))  N_REVIEW /*评审分小计*/
	FROM V_REVIEW_SUM_DATA T1
	GROUP BY T1.R_SID;

/*评审分汇总视图*/
CREATE OR REPLACE VIEW V_REVIEW_SUM AS
SELECT T1.*
	,CONVERT(
	IFNULL(T1.N_REVIEW,0) / IFNULL(T2.N_GET,0)*100
	,DECIMAL(4,1))  N_P /*百分制得分*/
	FROM V_REVIEW_SUM_DATA T1
	/*小计*/
	LEFT JOIN V_REVIEW_SUM_SUBTOTAL T2 ON T1.R_SID = T2.R_SID
UNION ALL
SELECT R_SID,'小计',99999,N_SUBTOTAL,N_BLANK,N_REAL,N_REVIEW,N_GET,CONVERT(
	IFNULL(N_REVIEW,0) / IFNULL(N_GET,0)*100
	,DECIMAL(4,1))  N_P
	FROM V_REVIEW_SUM_SUBTOTAL T3;

/*扣分汇总视图*/
CREATE OR REPLACE VIEW V_REVIEW_SUM_DED AS
	SELECT R_SID,C_CATEGORY,C_PROJECT,
	IFNULL(C_CONTENT,'') C_CONTENT,
	IFNULL(C_DESC,'') C_DESC,
	IFNULL(N_SCORE,0)-IFNULL(N_SCORE_REAL,0) N_DED
	FROM SSM_REVIEW_CONTENT
	WHERE IFNULL(N_SCORE_REVIEW,0)<IFNULL(N_SCORE,0)
	AND C_PROJECT<>'小计' AND C_PROJECT<>'总计'
	ORDER BY N_INDEX;