DROP TABLE IF EXISTS GEN_SEQUENCE;
CREATE TABLE GEN_SEQUENCE(
    C_NAME VARCHAR(32) PRIMARY KEY,
    N_VALUE INT DEFAULT 1,
    N_STEP INT DEFAULT 1
);

DELIMITER $$

DROP PROCEDURE IF EXISTS SP_GETSEQVALUE$$
CREATE PROCEDURE `SP_GETSEQVALUE`(
    IN C_NAME VARCHAR(32),
    IN N_LENGTH INT,
    INOUT C_PATTERN VARCHAR(200)
)
BEGIN
    DECLARE STR_RESULT VARCHAR(200);
    DECLARE STR_NAME VARCHAR(200) DEFAULT UPPER(C_NAME);

    START TRANSACTION;

    -- 查询当前的值
    SELECT CAST(A.N_VALUE AS CHAR) INTO STR_RESULT FROM GEN_SEQUENCE A WHERE A.C_NAME=STR_NAME;
    

    -- 如果当前值不存在则应该要插入数据
    IF STR_RESULT IS NULL THEN
        INSERT INTO `GEN_SEQUENCE`(C_NAME) VALUES(STR_NAME);
        -- 再次查询当前的值
	     SELECT CAST(A.N_VALUE AS CHAR) INTO STR_RESULT FROM GEN_SEQUENCE A WHERE A.C_NAME=STR_NAME;
    END IF;

    IF N_LENGTH > LENGTH(STR_RESULT) THEN
        SET STR_RESULT=LPAD(STR_RESULT, N_LENGTH, '0');
    END IF;
    SET C_PATTERN = REPLACE(C_PATTERN, '@', STR_RESULT);

    -- 更新当前的值
    UPDATE `GEN_SEQUENCE`
    SET `N_VALUE` = `N_VALUE`+`N_STEP`;

    COMMIT;
END$$

DELIMITER ;

-- 测试
/*
set @str_result = 'E350102@';
CALL sp_getSEQVALUE('E350102', '4', @str_result);
select @str_result;
*/