-- 隐患监管视图
CREATE OR REPLACE VIEW `ssms`.`v_task_trouble_supervision` AS
    (SELECT A.`S_TENANT`,A.`P_PROFESSION`,A.`T_CREATE`,B.`R_INDUSTRY`,B.`C_NAME` AS `S_PROFESSION`
,FLOOR(TRUNCATE(A.`N_FINISH_TROUBLE`/A.`N_ALL_TROUBLE`,2)*100) AS C_RECTIFICATION
,C.`P_PROVINCE`,C.`P_CITY`, C.`P_COUNTY`, C.`C_ADDR`,C.`P_AT_PROVINCE` ,C.`P_AT_CITY` , C.`P_AT_COUNTY`
    FROM `SYS_TASK_TROUBLE_SUPERVISION` A JOIN `sys_profession` B ON A.`P_PROFESSION`= B.`SID`
    JOIN `sys_tenant_e`  C ON A.`R_TENANT` = C.`SID`);