-- 初始化导航
delete from sys_nav;

insert into `sys_nav` (`SID`, `R_SID`, `C_NAME`, `C_URL`, `C_DESC`, `C_ICON`, `R_CREATE`, `S_CREATE`, `T_CREATE`, `R_UPDATE`, `S_UPDATE`, `T_UPDATE`, `R_TENANT`, `S_TENANT`, `P_TENANT`, `N_STATE`, `B_DELETE`, `N_INDEX`, `N_VERSION`) values('3','0','功能导航菜单','','123','agency',NULL,NULL,NULL,'0','admin','2015-05-22 14:55:25',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
insert into `sys_nav` (`SID`, `R_SID`, `C_NAME`, `C_URL`, `C_DESC`, `C_ICON`, `R_CREATE`, `S_CREATE`, `T_CREATE`, `R_UPDATE`, `S_UPDATE`, `T_UPDATE`, `R_TENANT`, `S_TENANT`, `P_TENANT`, `N_STATE`, `B_DELETE`, `N_INDEX`, `N_VERSION`) values('13','3','企业端导航',NULL,'aaa',NULL,'0','admin','2015-04-26 10:57:17','0','admin','2015-05-22 16:32:54','0','admin','S','0',NULL,'0','0');
insert into `sys_nav` (`SID`, `R_SID`, `C_NAME`, `C_URL`, `C_DESC`, `C_ICON`, `R_CREATE`, `S_CREATE`, `T_CREATE`, `R_UPDATE`, `S_UPDATE`, `T_UPDATE`, `R_TENANT`, `S_TENANT`, `P_TENANT`, `N_STATE`, `B_DELETE`, `N_INDEX`, `N_VERSION`) values('14','3','评审端导航','','','','0','admin','2015-04-26 10:57:26','0','admin','2015-05-22 14:55:26','0','admin','S','0','','0','0');
insert into `sys_nav` (`SID`, `R_SID`, `C_NAME`, `C_URL`, `C_DESC`, `C_ICON`, `R_CREATE`, `S_CREATE`, `T_CREATE`, `R_UPDATE`, `S_UPDATE`, `T_UPDATE`, `R_TENANT`, `S_TENANT`, `P_TENANT`, `N_STATE`, `B_DELETE`, `N_INDEX`, `N_VERSION`) values('15','3','政府端导航','','','','0','admin','2015-04-26 10:57:33','0','admin','2015-05-22 14:55:27','0','admin','S','0','','0','0');
insert into `sys_nav` (`SID`, `R_SID`, `C_NAME`, `C_URL`, `C_DESC`, `C_ICON`, `R_CREATE`, `S_CREATE`, `T_CREATE`, `R_UPDATE`, `S_UPDATE`, `T_UPDATE`, `R_TENANT`, `S_TENANT`, `P_TENANT`, `N_STATE`, `B_DELETE`, `N_INDEX`, `N_VERSION`) values('16','3','系统运维端导航','','','','0','admin','2015-04-26 10:57:46','0','admin','2015-05-22 14:55:28','0','admin','S','0','','0','0');
insert into `sys_nav` (`SID`, `R_SID`, `C_NAME`, `C_URL`, `C_DESC`, `C_ICON`, `R_CREATE`, `S_CREATE`, `T_CREATE`, `R_UPDATE`, `S_UPDATE`, `T_UPDATE`, `R_TENANT`, `S_TENANT`, `P_TENANT`, `N_STATE`, `B_DELETE`, `N_INDEX`, `N_VERSION`) values('18','13','13要素自主创建','/e/stdtmp/','','nav-info','0','admin','2015-04-26 10:58:42','-1','admin','2015-05-22 14:55:02','0','admin','S','0','','0','0');
insert into `sys_nav` (`SID`, `R_SID`, `C_NAME`, `C_URL`, `C_DESC`, `C_ICON`, `R_CREATE`, `S_CREATE`, `T_CREATE`, `R_UPDATE`, `S_UPDATE`, `T_UPDATE`, `R_TENANT`, `S_TENANT`, `P_TENANT`, `N_STATE`, `B_DELETE`, `N_INDEX`, `N_VERSION`) values('19','13','在线自评','/e/grade_m/','','gongwen','0','admin','2015-04-26 10:58:58','1','admin','2015-05-22 14:55:02','0','admin','S','0','','0','0');
insert into `sys_nav` (`SID`, `R_SID`, `C_NAME`, `C_URL`, `C_DESC`, `C_ICON`, `R_CREATE`, `S_CREATE`, `T_CREATE`, `R_UPDATE`, `S_UPDATE`, `T_UPDATE`, `R_TENANT`, `S_TENANT`, `P_TENANT`, `N_STATE`, `B_DELETE`, `N_INDEX`, `N_VERSION`) values('20','16','系统配置','','','nav-info','0','admin','2015-04-27 11:33:24','0','admin','2015-05-22 14:55:29','0','admin','S','0','','3','0');
insert into `sys_nav` (`SID`, `R_SID`, `C_NAME`, `C_URL`, `C_DESC`, `C_ICON`, `R_CREATE`, `S_CREATE`, `T_CREATE`, `R_UPDATE`, `S_UPDATE`, `T_UPDATE`, `R_TENANT`, `S_TENANT`, `P_TENANT`, `N_STATE`, `B_DELETE`, `N_INDEX`, `N_VERSION`) values('21','20','系统导航配置','/sys/nav/','','','0','admin','2015-04-27 11:33:44','0','admin','2015-05-22 14:55:02','0','admin','S','0','','99','0');

insert into `sys_nav` (`SID`, `R_SID`, `C_NAME`, `C_URL`, `C_DESC`, `C_ICON`, `R_CREATE`, `S_CREATE`, `T_CREATE`, `R_UPDATE`, `S_UPDATE`, `T_UPDATE`, `R_TENANT`, `S_TENANT`, `P_TENANT`, `N_STATE`, `B_DELETE`, `N_INDEX`, `N_VERSION`) values('38','14','评审办理','/r/grade_m/index','','do','1','admin','2015-05-15 09:46:41','4','管理员','2015-05-29 01:14:40','1','admin','S',NULL,NULL,'1',NULL);
insert into `sys_nav` (`SID`, `R_SID`, `C_NAME`, `C_URL`, `C_DESC`, `C_ICON`, `R_CREATE`, `S_CREATE`, `T_CREATE`, `R_UPDATE`, `S_UPDATE`, `T_UPDATE`, `R_TENANT`, `S_TENANT`, `P_TENANT`, `N_STATE`, `B_DELETE`, `N_INDEX`, `N_VERSION`) values('46','14','评审历史','/r/grade_m/history','','history','1','admin','2015-05-15 09:47:25','4','管理员','2015-05-29 01:14:46','1','admin','S',NULL,NULL,'2',NULL);
insert into `sys_nav` (`SID`, `R_SID`, `C_NAME`, `C_URL`, `C_DESC`, `C_ICON`, `R_CREATE`, `S_CREATE`, `T_CREATE`, `R_UPDATE`, `S_UPDATE`, `T_UPDATE`, `R_TENANT`, `S_TENANT`, `P_TENANT`, `N_STATE`, `B_DELETE`, `N_INDEX`, `N_VERSION`) values('47','14','统计分析','/r/statistics/','','statistics','1','admin','2015-05-15 09:47:25','4','管理员','2015-05-29 01:14:46','1','admin','S',NULL,NULL,'3',NULL);
insert into `sys_nav` (`SID`, `R_SID`, `C_NAME`, `C_URL`, `C_DESC`, `C_ICON`, `R_CREATE`, `S_CREATE`, `T_CREATE`, `R_UPDATE`, `S_UPDATE`, `T_UPDATE`, `R_TENANT`, `S_TENANT`, `P_TENANT`, `N_STATE`, `B_DELETE`, `N_INDEX`, `N_VERSION`) values('48','14','通知公告','/r/notice/','','notice','1','admin','2015-05-15 09:47:25','4','管理员','2015-05-29 01:14:46','1','admin','S',NULL,NULL,'4',NULL);
insert into `sys_nav` (`SID`, `R_SID`, `C_NAME`, `C_URL`, `C_DESC`, `C_ICON`, `R_CREATE`, `S_CREATE`, `T_CREATE`, `R_UPDATE`, `S_UPDATE`, `T_UPDATE`, `R_TENANT`, `S_TENANT`, `P_TENANT`, `N_STATE`, `B_DELETE`, `N_INDEX`, `N_VERSION`) values('49','14','知识库','/r/knowledge/','','knowledge','1','admin','2015-05-15 09:47:25','4','管理员','2015-05-29 01:14:46','1','admin','S',NULL,NULL,'5',NULL);
insert into `sys_nav` (`SID`, `R_SID`, `C_NAME`, `C_URL`, `C_DESC`, `C_ICON`, `R_CREATE`, `S_CREATE`, `T_CREATE`, `R_UPDATE`, `S_UPDATE`, `T_UPDATE`, `R_TENANT`, `S_TENANT`, `P_TENANT`, `N_STATE`, `B_DELETE`, `N_INDEX`, `N_VERSION`) values('50','14','设置','/r/config/','','config','1','admin','2015-05-15 09:47:25','4','管理员','2015-05-29 01:14:46','1','admin','S',NULL,NULL,'6',NULL);

insert into `sys_nav` (`SID`, `R_SID`, `C_NAME`, `C_URL`, `C_DESC`, `C_ICON`, `R_CREATE`, `S_CREATE`, `T_CREATE`, `R_UPDATE`, `S_UPDATE`, `T_UPDATE`, `R_TENANT`, `S_TENANT`, `P_TENANT`, `N_STATE`, `B_DELETE`, `N_INDEX`, `N_VERSION`) values('27','20','专业管理','/sys/profession/','','','0','admin','2015-04-27 23:44:33','0','admin','2015-05-22 14:55:02','0','admin','S','0','','3','0');
insert into `sys_nav` (`SID`, `R_SID`, `C_NAME`, `C_URL`, `C_DESC`, `C_ICON`, `R_CREATE`, `S_CREATE`, `T_CREATE`, `R_UPDATE`, `S_UPDATE`, `T_UPDATE`, `R_TENANT`, `S_TENANT`, `P_TENANT`, `N_STATE`, `B_DELETE`, `N_INDEX`, `N_VERSION`) values('28','16','租户管理','','','agency','0','admin','2015-04-28 09:35:16','0','admin','2015-05-22 14:55:31','0','admin','S','0','','2','0');
insert into `sys_nav` (`SID`, `R_SID`, `C_NAME`, `C_URL`, `C_DESC`, `C_ICON`, `R_CREATE`, `S_CREATE`, `T_CREATE`, `R_UPDATE`, `S_UPDATE`, `T_UPDATE`, `R_TENANT`, `S_TENANT`, `P_TENANT`, `N_STATE`, `B_DELETE`, `N_INDEX`, `N_VERSION`) values('29','28','企业租户管理','/sys/tenant_e/','','','0','admin','2015-04-28 09:36:07','0','admin','2015-05-22 14:55:02','0','admin','S','0','','0','0');
insert into `sys_nav` (`SID`, `R_SID`, `C_NAME`, `C_URL`, `C_DESC`, `C_ICON`, `R_CREATE`, `S_CREATE`, `T_CREATE`, `R_UPDATE`, `S_UPDATE`, `T_UPDATE`, `R_TENANT`, `S_TENANT`, `P_TENANT`, `N_STATE`, `B_DELETE`, `N_INDEX`, `N_VERSION`) values('30','28','政府租户管理','/sys/tenant_g/','','','0','admin','2015-04-28 09:37:51','0','admin','2015-05-22 14:55:02','0','admin','S','0','','0','0');
insert into `sys_nav` (`SID`, `R_SID`, `C_NAME`, `C_URL`, `C_DESC`, `C_ICON`, `R_CREATE`, `S_CREATE`, `T_CREATE`, `R_UPDATE`, `S_UPDATE`, `T_UPDATE`, `R_TENANT`, `S_TENANT`, `P_TENANT`, `N_STATE`, `B_DELETE`, `N_INDEX`, `N_VERSION`) values('31','28','评审机构租户管理','/sys/tenant_r/','','','0','admin','2015-04-28 09:40:12','0','admin','2015-05-22 14:55:02','0','admin','S','0','','0','0');
insert into `sys_nav` (`SID`, `R_SID`, `C_NAME`, `C_URL`, `C_DESC`, `C_ICON`, `R_CREATE`, `S_CREATE`, `T_CREATE`, `R_UPDATE`, `S_UPDATE`, `T_UPDATE`, `R_TENANT`, `S_TENANT`, `P_TENANT`, `N_STATE`, `B_DELETE`, `N_INDEX`, `N_VERSION`) values('32','15','通知公告','','','','0','admin','2015-05-01 07:59:44',NULL,NULL,'2015-05-22 14:55:34','0','admin','S',NULL,NULL,NULL,NULL);
insert into `sys_nav` (`SID`, `R_SID`, `C_NAME`, `C_URL`, `C_DESC`, `C_ICON`, `R_CREATE`, `S_CREATE`, `T_CREATE`, `R_UPDATE`, `S_UPDATE`, `T_UPDATE`, `R_TENANT`, `S_TENANT`, `P_TENANT`, `N_STATE`, `B_DELETE`, `N_INDEX`, `N_VERSION`) values('33','32','已发布的通知公告','/g/notice/publics/','','','0','admin','2015-05-01 08:00:19','0','admin','2015-05-22 14:55:02','0','admin','S',NULL,NULL,NULL,NULL);
insert into `sys_nav` (`SID`, `R_SID`, `C_NAME`, `C_URL`, `C_DESC`, `C_ICON`, `R_CREATE`, `S_CREATE`, `T_CREATE`, `R_UPDATE`, `S_UPDATE`, `T_UPDATE`, `R_TENANT`, `S_TENANT`, `P_TENANT`, `N_STATE`, `B_DELETE`, `N_INDEX`, `N_VERSION`) values('34','32','草稿箱','/g/notice/drafts/','','','0','admin','2015-05-01 08:00:35','0','admin','2015-05-22 14:55:02','0','admin','S',NULL,NULL,NULL,NULL);
insert into `sys_nav` (`SID`, `R_SID`, `C_NAME`, `C_URL`, `C_DESC`, `C_ICON`, `R_CREATE`, `S_CREATE`, `T_CREATE`, `R_UPDATE`, `S_UPDATE`, `T_UPDATE`, `R_TENANT`, `S_TENANT`, `P_TENANT`, `N_STATE`, `B_DELETE`, `N_INDEX`, `N_VERSION`) values('35','20','模板管理','/sys/template/','','','0','admin','2015-05-05 11:50:44',NULL,NULL,'2015-05-22 14:55:02','0','admin','S',NULL,NULL,'1',NULL);
insert into `sys_nav` (`SID`, `R_SID`, `C_NAME`, `C_URL`, `C_DESC`, `C_ICON`, `R_CREATE`, `S_CREATE`, `T_CREATE`, `R_UPDATE`, `S_UPDATE`, `T_UPDATE`, `R_TENANT`, `S_TENANT`, `P_TENANT`, `N_STATE`, `B_DELETE`, `N_INDEX`, `N_VERSION`) values('36','20','行业管理','/sys/industry/','','','1','admin','2015-05-14 23:11:43',NULL,NULL,'2015-05-22 14:55:02','1','admin','S',NULL,NULL,'2',NULL);
insert into `sys_nav` (`SID`, `R_SID`, `C_NAME`, `C_URL`, `C_DESC`, `C_ICON`, `R_CREATE`, `S_CREATE`, `T_CREATE`, `R_UPDATE`, `S_UPDATE`, `T_UPDATE`, `R_TENANT`, `S_TENANT`, `P_TENANT`, `N_STATE`, `B_DELETE`, `N_INDEX`, `N_VERSION`) values('37','20','参数管理','/sys/para_multi/','','','1','admin','2015-05-14 23:11:43',NULL,NULL,'2015-05-22 14:55:02','1','admin','S',NULL,NULL,'98',NULL);
insert into `sys_nav` (`SID`, `R_SID`, `C_NAME`, `C_URL`, `C_DESC`, `C_ICON`, `R_CREATE`, `S_CREATE`, `T_CREATE`, `R_UPDATE`, `S_UPDATE`, `T_UPDATE`, `R_TENANT`, `S_TENANT`, `P_TENANT`, `N_STATE`, `B_DELETE`, `N_INDEX`, `N_VERSION`) values('43','13','数据统计','/development/','','','1','admin','2015-05-16 10:50:39','1','admin','2015-05-22 14:55:02','1','admin','S','0','','1','0');
insert into `sys_nav` (`SID`, `R_SID`, `C_NAME`, `C_URL`, `C_DESC`, `C_ICON`, `R_CREATE`, `S_CREATE`, `T_CREATE`, `R_UPDATE`, `S_UPDATE`, `T_UPDATE`, `R_TENANT`, `S_TENANT`, `P_TENANT`, `N_STATE`, `B_DELETE`, `N_INDEX`, `N_VERSION`) values('44','13','知识库','/development/','','','1','admin','2015-05-16 10:50:39','1','admin','2015-05-22 14:55:02','1','admin','S','0','','2','0');
insert into `sys_nav` (`SID`, `R_SID`, `C_NAME`, `C_URL`, `C_DESC`, `C_ICON`, `R_CREATE`, `S_CREATE`, `T_CREATE`, `R_UPDATE`, `S_UPDATE`, `T_UPDATE`, `R_TENANT`, `S_TENANT`, `P_TENANT`, `N_STATE`, `B_DELETE`, `N_INDEX`, `N_VERSION`) values('45','13','设置','/development/','','','1','admin','2015-05-16 10:50:39','1','admin','2015-05-22 14:55:02','1','admin','S','0','','3','0');
