/*租户用户列表*/
CREATE OR REPLACE VIEW TENANT_USER AS
    SELECT A.`C_NAME` TENANT_NAME, UPPER(A.`C_CODE`) TENANT_CODE, SUBSTR(UPPER(A.`C_CODE`), 1, 1) TENANT_TYPE, A.`SID` TENANT_ID, B.`C_NAME` USER_NAME, UPPER(B.`C_USER`) USER_CODE, UPPER(B.`C_PASSWD`) USER_PASSWORD, B.`SID` USER_ID
    FROM SYS_TENANT_E A INNER JOIN SYS_TENANT_E_USER B ON A.`SID` = B.`R_SID`
    WHERE IFNULL(A.B_DELETE, 0) = 0
    UNION ALL
    SELECT A.`C_NAME` TENANT_NAME, UPPER(A.`C_CODE`) TENANT_CODE, SUBSTR(UPPER(A.`C_CODE`), 1, 1) TENANT_TYPE, A.`SID` TENANT_ID, B.`C_NAME` USER_NAME, UPPER(B.`C_USER`) USER_CODE, UPPER(B.`C_PASSWD`) USER_PASSWORD, B.`SID` USER_ID
    FROM SYS_TENANT_R A INNER JOIN SYS_TENANT_R_USER B ON A.`SID` = B.`R_SID`
    WHERE IFNULL(A.B_DELETE, 0) = 0
    UNION ALL
    SELECT A.`C_NAME` TENANT_NAME, UPPER(A.`C_CODE`) TENANT_CODE, SUBSTR(UPPER(A.`C_CODE`), 1, 1) TENANT_TYPE, A.`SID` TENANT_ID, B.`C_NAME` USER_NAME, UPPER(B.`C_USER`) USER_CODE, UPPER(B.`C_PASSWD`) USER_PASSWORD, B.`SID` USER_ID
    FROM SYS_TENANT_G A INNER JOIN SYS_TENANT_G_USER B ON A.`SID` = B.`R_SID`
    WHERE IFNULL(A.B_DELETE, 0) = 0
    UNION ALL
    SELECT '系统用户' TENANT_NAME, 'SYSTEM' TENANT_CODE, 'S' TENANT_TYPE, 0 TENANT_ID, A.`C_NAME` USER_NAME, UPPER(A.C_NAME) USER_CODE, UPPER(A.`C_PASSWD`) USER_PASSWORD, A.`SID` USER_ID
    FROM SYS_USER A
;


/*企业视图*/
CREATE OR REPLACE VIEW V_TENANT_E AS
	SELECT t1.SID,t1.C_NAME,t1.C_CODE,
	t1.C_ADDR,t1.C_CONTACT,t1.C_TEL,
	t1.N_STATE,t1.P_PROVINCE,t1.P_CITY,t1.P_COUNTY,
	t2.P_PROFESSION,t2.S_PROFESSION C_NAME_PRO,
	t3.C_NAME C_NAME_IND
	FROM SYS_TENANT_E t1
	LEFT JOIN sys_tenant_e_profession t2 ON t1.sid=t2.R_TENANT
	LEFT JOIN sys_industry t3 ON t1.R_INDUSTRY=t3.SID
	ORDER BY t1.N_INDEX,t1.SID;