DROP TABLE IF EXISTS `SYS_TASK_HIDDEN_DANGER`;
CREATE TABLE `SYS_TASK_HIDDEN_DANGER` (
    `SID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `R_TEMPLATE` INT(11) COMMENT '所属模板',
    `R_TENANT` INT(11) COMMENT '租户编号',
    `S_TENANT` VARCHAR(300) COMMENT '租户名称',
    `P_TENANT` CHAR(1) COMMENT '租户类型',
    `P_PROFESSION` INT(11) COMMENT '所属专业ID',
    `T_CREATE`  DATE NULL  COMMENT '创建日期',
     PRIMARY KEY (`SID`)
);

DROP TABLE IF EXISTS `SYS_HIS_TASK_HIDDEN_DANGER`;
CREATE TABLE `SYS_HIS_TASK_HIDDEN_DANGER` (
    `SID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `R_TENANT` INT(11) COMMENT '租户编号',
    `S_TENANT` VARCHAR(300) COMMENT '租户名称',
    `P_TENANT` CHAR(1) COMMENT '租户类型',
    `R_SID` INT(11) COMMENT '定时任务ID',
     PRIMARY KEY (`SID`)
);
