 /*通知公告*/		
CREATE OR REPLACE VIEW V_NOTICE AS
 SELECT T1.*,T2.R_RECEIVER,T2.S_RECEIVER,T2.Z_TYPE 
 FROM SYS_NOTICE T1 
 INNER JOIN SYS_NOTICE_RECEIVER T2 ON T1.SID=T2.R_NOTICE 
 WHERE 
 T1.R_PUBLISH IS NOT NULL 
 ORDER BY T1.T_PUBLISH DESC;