DELIMITER $$

ALTER TABLE SSM_GRADE_PLAN ADD COLUMN N_COUNT INT(11);

ALTER TABLE SSM_REVIEW_PLAN ADD COLUMN C_JOB VARCHAR(200);

DROP PROCEDURE IF EXISTS `P_GRADE_INIT`$$
DROP PROCEDURE IF EXISTS `P_GRADE_SUM`$$
DROP PROCEDURE IF EXISTS `P_GRADE_SUM_R`$$
DROP PROCEDURE IF EXISTS `P_GRADE_COMPLETE_E`$$
DROP PROCEDURE IF EXISTS `P_GRADE_COMPLETE_R`$$
DROP PROCEDURE IF EXISTS `SP_FILE_REMIND`$$


/*自评统计项*/
DROP PROCEDURE IF EXISTS `P_GRADE_SUM`$$
CREATE PROCEDURE P_GRADE_SUM(IN IN_SID INT)  
    BEGIN
	/*得分、扣分、缺项统计*/
	UPDATE ssm_grade_plan T1 
	LEFT JOIN (SELECT R_SID,COUNT(*)  N FROM SSM_GRADE_CONTENT  
		WHERE IFNULL(C_PROJECT,'')<>'总计' AND IFNULL(C_PROJECT,'')<>'小计'  AND N_SCORE_REAL IS NOT NULL  AND N_SCORE_REAL=N_SCORE GROUP BY R_SID) T2 ON T1.SID = T2.R_SID
	LEFT JOIN (SELECT R_SID,COUNT(*)  N FROM SSM_GRADE_CONTENT 
		WHERE IFNULL(C_PROJECT,'')<>'总计' AND IFNULL(C_PROJECT,'')<>'小计'  AND N_SCORE_REAL IS NOT NULL  AND N_SCORE_REAL<N_SCORE  GROUP BY R_SID) T3 ON T1.SID = T3.R_SID
	LEFT JOIN (SELECT R_SID,COUNT(*)  N FROM SSM_GRADE_CONTENT 
		WHERE IFNULL(C_PROJECT,'')<>'总计' AND IFNULL(C_PROJECT,'')<>'小计'  AND B_BLANK='1'  GROUP BY R_SID) T4 ON T1.SID = T4.R_SID
	SET T1.N_GET=IFNULL(T2.N,0),T1.N_DEDUCT=IFNULL(T3.N,0),T1.N_LACK=IFNULL(T4.N,0)
	WHERE T1.SID=IN_SID;
	
	/*得分小计*/
	UPDATE SSM_GRADE_CONTENT T1
	LEFT JOIN (SELECT C_CATEGORY,SUM(N_SCORE_REAL) N FROM SSM_GRADE_CONTENT 
		WHERE R_SID=IN_SID AND IFNULL(C_PROJECT,'')<>'总计' AND IFNULL(C_PROJECT,'')<>'小计'   GROUP BY C_CATEGORY) T2 ON T1.C_CATEGORY = T2.C_CATEGORY
	SET T1.N_SCORE_REAL=T2.N
	WHERE T1.C_CATEGORY=T2.C_CATEGORY
	AND T1.C_PROJECT='小计' AND T1.R_SID=IN_SID;
	
	/*总计*/
	UPDATE SSM_GRADE_CONTENT T1
	,(SELECT SUM(N_SCORE_REAL) N FROM SSM_GRADE_CONTENT WHERE R_SID=IN_SID AND C_PROJECT='小计' ) T2
	SET T1.N_SCORE_REAL=T2.N
	WHERE T1.R_SID=IN_SID 
	AND T1.C_PROJECT='总计' AND T1.R_SID=IN_SID;
    END$$


/*评审统计项*/
DROP PROCEDURE IF EXISTS `P_REVIEW_SUM`$$
CREATE PROCEDURE P_REVIEW_SUM(IN IN_SID INT)  
    BEGIN
	/*得分小计*/
	UPDATE SSM_REVIEW_CONTENT T1
	LEFT JOIN (SELECT C_CATEGORY,SUM(N_SCORE_REVIEW) N FROM SSM_REVIEW_CONTENT 
		WHERE R_SID=IN_SID AND IFNULL(C_PROJECT,'')<>'总计' AND IFNULL(C_PROJECT,'')<>'小计'   GROUP BY C_CATEGORY) T2 ON T1.C_CATEGORY = T2.C_CATEGORY
	SET T1.N_SCORE_REVIEW=T2.N
	WHERE T1.C_CATEGORY=T2.C_CATEGORY
	AND T1.C_PROJECT='小计' AND T1.R_SID=IN_SID;
	
	/*总计*/
	UPDATE SSM_REVIEW_CONTENT T1
	,(SELECT SUM(N_SCORE_REVIEW) N FROM SSM_REVIEW_CONTENT WHERE R_SID=IN_SID AND C_PROJECT='小计' ) T2
	SET T1.N_SCORE_REVIEW=T2.N
	WHERE T1.R_SID=IN_SID 
	AND T1.C_PROJECT='总计' AND T1.R_SID=IN_SID;
    END$$

DELIMITER ;