ALTER TABLE `sys_tenant_e`
    ADD COLUMN `P_AT_PROVINCE` VARCHAR(32) NULL DEFAULT NULL COMMENT '所属辖区省份编号' AFTER `S_STATE`,
    ADD COLUMN `S_AT_PROVINCE` VARCHAR(100) NULL DEFAULT NULL COMMENT '所属辖区省份' AFTER `P_AT_PROVINCE`,
    ADD COLUMN `P_AT_CITY` VARCHAR(32) NULL DEFAULT NULL COMMENT '所属辖区地市编号' AFTER `S_AT_PROVINCE`,
    ADD COLUMN `S_AT_CITY` VARCHAR(100) NULL DEFAULT NULL COMMENT '所属辖区地市' AFTER `P_AT_CITY`,
    ADD COLUMN `P_AT_COUNTY` VARCHAR(32) NULL DEFAULT NULL COMMENT '所属辖区地县编号' AFTER `S_AT_CITY`,
    ADD COLUMN `S_AT_COUNTY` VARCHAR(100) NULL DEFAULT NULL COMMENT '所属辖区地县' AFTER `P_AT_COUNTY`;
