DELIMITER $$
/*评分汇总——数据*/
CREATE OR REPLACE VIEW V_GRADE_SUM_DATA_R AS
SELECT T1.R_SID, T1.C_PROJECT,T1.N_INDEX
	,SUM(IFNULL(T1.N_SCORE,0)) N_SUBTOTAL /*项目标准分值小计*/
	,IFNULL(T2.N,0) N_BLANK/*空项分*/
	,IFNULL(T3.N,0) N_REAL /*企业自评得分*/
	,IFNULL(T4.N,0) N_REVIEW /*评审得分*/
	,SUM(IFNULL(T1.N_SCORE,0)) -IFNULL(T2.N,0) N_GET/*应得分*/
	FROM SSM_GRADE_R_D T1 
	/*空项分*/
	LEFT JOIN V_GRADE_SUM_BLANK_R T2 
		ON T1.R_SID = T2.R_SID AND T1.C_PROJECT=T2.C_PROJECT
	/*企业自评得分*/
	LEFT JOIN  V_GRADE_SUM_REAL_R T3 
			ON T1.R_SID = T3.R_SID AND T1.C_PROJECT=T3.C_PROJECT	
	/*评审得分*/
	LEFT JOIN  V_GRADE_SUM_REVIEW T4 
			ON T1.R_SID = T4.R_SID AND T1.C_PROJECT=T4.C_PROJECT

	WHERE T1.C_PROJECT<>'总计' AND T1.C_PROJECT<>'小计' 
	GROUP BY T1.R_SID,T1.C_PROJECT 	
	ORDER BY N_INDEX;$$

DELIMITER ;