DELIMITER $$

/*评审统计项*/
DROP PROCEDURE IF EXISTS `P_GRADE_SUM_R`$$
CREATE PROCEDURE P_GRADE_SUM_R(IN IN_SID INT)  
    BEGIN
	/*得分、扣分、缺项统计*/
	UPDATE SSM_GRADE_R_M T1 
	LEFT JOIN (SELECT R_SID,COUNT(*)  N FROM SSM_GRADE_R_D  
		WHERE IFNULL(C_PROJECT,'')<>'总计' AND IFNULL(C_PROJECT,'')<>'小计'  AND N_SCORE_REVIEW IS NOT NULL  AND N_SCORE_REVIEW=N_SCORE GROUP BY R_SID) T2 ON T1.SID = T2.R_SID
	LEFT JOIN (SELECT R_SID,COUNT(*)  N FROM SSM_GRADE_R_D 
		WHERE IFNULL(C_PROJECT,'')<>'总计' AND IFNULL(C_PROJECT,'')<>'小计'  AND N_SCORE_REVIEW IS NOT NULL  AND N_SCORE_REVIEW<N_SCORE  GROUP BY R_SID) T3 ON T1.SID = T3.R_SID
	LEFT JOIN (SELECT R_SID,COUNT(*)  N FROM SSM_GRADE_R_D 
		WHERE IFNULL(C_PROJECT,'')<>'总计' AND IFNULL(C_PROJECT,'')<>'小计'  AND B_BLANK='1'  GROUP BY R_SID) T4 ON T1.SID = T4.R_SID
	SET T1.N_GET=IFNULL(T2.N,0),T1.N_DEDUCT=IFNULL(T3.N,0),T1.N_LACK=IFNULL(T4.N,0)
	WHERE T1.SID=IN_SID;
	
	/*得分小计*/
	UPDATE SSM_GRADE_R_D T1
	LEFT JOIN (SELECT C_CATEGORY,SUM(N_SCORE_REVIEW) N FROM SSM_GRADE_R_D 
		WHERE R_SID=IN_SID AND IFNULL(C_PROJECT,'')<>'总计' AND IFNULL(C_PROJECT,'')<>'小计'   GROUP BY C_CATEGORY) T2 ON T1.C_CATEGORY = T2.C_CATEGORY
	SET T1.N_SCORE_REVIEW=T2.N
	WHERE T1.C_CATEGORY=T2.C_CATEGORY
	AND T1.C_PROJECT='小计' AND T1.R_SID=IN_SID;
	
	/*总计*/
	UPDATE SSM_GRADE_R_D T1
	,(SELECT SUM(N_SCORE_REVIEW) N FROM SSM_GRADE_R_D WHERE R_SID=IN_SID AND C_PROJECT='小计' ) T2
	SET T1.N_SCORE_REVIEW=T2.N
	WHERE T1.R_SID=IN_SID 
	AND T1.C_PROJECT='总计' AND T1.R_SID=IN_SID;
    END$$





/*评分汇总——空项分*/
CREATE OR REPLACE VIEW V_GRADE_SUM_BLANK_R AS
SELECT R_SID,C_PROJECT,SUM(IFNULL(N_SCORE_REVIEW,0))  N FROM SSM_GRADE_R_D 
		WHERE C_PROJECT<>'总计' AND C_PROJECT<>'小计'  
	 GROUP BY R_SID,C_PROJECT;$$
		
/*评分汇总——实际得分*/		
CREATE OR REPLACE VIEW V_GRADE_SUM_REAL_R AS
SELECT R_SID,C_PROJECT,SUM(IFNULL(N_SCORE_REAL,0))  N FROM SSM_GRADE_R_D  
			WHERE C_PROJECT<>'总计' AND C_PROJECT<>'小计'  
	GROUP BY R_SID,C_PROJECT;$$

/*评分汇总——实际得分*/		
CREATE OR REPLACE VIEW V_GRADE_SUM_REVIEW AS
SELECT R_SID,C_PROJECT,SUM(IFNULL(N_SCORE_REVIEW,0))  N FROM SSM_GRADE_R_D  
			WHERE C_PROJECT<>'总计' AND C_PROJECT<>'小计'  
	GROUP BY R_SID,C_PROJECT;$$
					
/*评分汇总——数据*/
CREATE OR REPLACE VIEW V_GRADE_SUM_DATA_R AS
SELECT T1.R_SID, T1.C_PROJECT,T1.N_INDEX
	,SUM(IFNULL(T1.N_SCORE,0)) N_SUBTOTAL /*项目标准分值小计*/
	,IFNULL(T2.N,0) N_BLANK/*空项分*/
	,IFNULL(T3.N,0) N_REAL /*企业自评得分*/
	,IFNULL(T4.N,0) N_REVIEW /*评审得分*/
	,SUM(IFNULL(T1.N_SCORE,0)) -IFNULL(T2.N,0) N_GET/*应得分*/
	FROM SSM_GRADE_E_D T1 
	/*空项分*/
	LEFT JOIN V_GRADE_SUM_BLANK_R T2 
		ON T1.R_SID = T2.R_SID AND T1.C_PROJECT=T2.C_PROJECT
	/*企业自评得分*/
	LEFT JOIN  V_GRADE_SUM_REAL_R T3 
			ON T1.R_SID = T3.R_SID AND T1.C_PROJECT=T3.C_PROJECT	
	/*评审得分*/
	LEFT JOIN  V_GRADE_SUM_REVIEW T4 
			ON T1.R_SID = T4.R_SID AND T1.C_PROJECT=T4.C_PROJECT

	WHERE T1.C_PROJECT<>'总计' AND T1.C_PROJECT<>'小计' 
	GROUP BY T1.R_SID,T1.C_PROJECT 	
	ORDER BY N_INDEX;$$
	
/*评分汇总——小计*/	
CREATE OR REPLACE VIEW V_GRADE_SUM_SUBTOTAL_R AS
SELECT T1.R_SID
	,SUM(IFNULL(T1.N_SUBTOTAL,0)) N_SUBTOTAL /*项目标准分值小计*/
	,SUM(IFNULL(T1.N_BLANK,0)) N_BLANK/*空项分小计*/
	,SUM(IFNULL(T1.N_REAL,0)) N_REAL /*实际得分小计*/
	,SUM(IFNULL(T1.N_GET,0))  N_GET /*应得分小计*/
	,SUM(IFNULL(T1.N_REVIEW,0))  N_REVIEW /*评审分小计*/
	FROM V_GRADE_SUM_DATA_R T1 
	GROUP BY T1.R_SID;$$

/*评分汇总视图*/
CREATE OR REPLACE VIEW V_GRADE_SUM_R AS
SELECT T1.*
	,CONVERT(
	IFNULL(T1.N_REVIEW,0) / IFNULL(T2.N_GET,0)*100
	,DECIMAL(4,1))  N_P /*百分制得分*/
	FROM V_GRADE_SUM_DATA_R T1 
	/*小计*/
	LEFT JOIN V_GRADE_SUM_SUBTOTAL_R T2 
		ON T1.R_SID = T2.R_SID
UNION ALL
SELECT R_SID,'小计',99999,N_SUBTOTAL,N_BLANK,N_REAL,N_REVIEW,N_GET,CONVERT(
	IFNULL(N_REVIEW,0) / IFNULL(N_GET,0)*100
	,DECIMAL(4,1))  N_P 
	FROM V_GRADE_SUM_SUBTOTAL_R T3;$$

		
/*扣分汇总视图*/
CREATE OR REPLACE VIEW V_GRADE_SUM_DED_R AS
	SELECT R_SID,C_CATEGORY,C_PROJECT,
	IFNULL(C_CONTENT,'') C_CONTENT,
	IFNULL(C_DESC,'') C_DESC,
	IFNULL(N_SCORE,0)-IFNULL(N_SCORE_REAL,0) N_DED
	FROM SSM_GRADE_R_D
	WHERE IFNULL(N_SCORE_REVIEW,0)<IFNULL(N_SCORE,0) 
	AND C_PROJECT<>'小计' AND C_PROJECT<>'总计'
	ORDER BY N_INDEX;$$

DELIMITER ;