-- 移除无用的字段
ALTER TABLE `ssm_stdtmp_file`
    DROP COLUMN `R_SOURCE`;
ALTER TABLE `ssm_stdtmp_folder`
    DROP COLUMN `R_SOURCE`;

-- 创建归档表
create table sys_template_arch like sys_template;
create table sys_stdtmp_folder_arch like sys_stdtmp_folder;
create table sys_stdtmp_file_arch like sys_stdtmp_file;
create table sys_stdtmp_file_01_arch like sys_stdtmp_file_01;
create table sys_stdtmp_file_02_arch like sys_stdtmp_file_02;
create table sys_stdtmp_file_03_arch like sys_stdtmp_file_03;
create table sys_stdtmp_file_04_arch like sys_stdtmp_file_04;
create table sys_stdtmp_file_06_arch like sys_stdtmp_file_06;
create table sys_stdtmp_file_07_arch like sys_stdtmp_file_07;
create table sys_stdtmp_file_08_arch like sys_stdtmp_file_08;
create table sys_stdtmp_file_09_arch like sys_stdtmp_file_09;

ALTER TABLE `sys_template_arch`
    ADD COLUMN `UID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '内部ID' FIRST,
    CHANGE COLUMN `SID` `SID` INT(11) NULL COMMENT '归档前的ID' AFTER `UID`,
    DROP PRIMARY KEY,
    ADD PRIMARY KEY (`UID`);
ALTER TABLE `sys_stdtmp_folder_arch`
    ADD COLUMN `UID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '内部ID' FIRST,
    CHANGE COLUMN `SID` `SID` INT(11) NULL COMMENT '归档前的ID' AFTER `UID`,
    DROP PRIMARY KEY,
    ADD PRIMARY KEY (`UID`);
ALTER TABLE `sys_stdtmp_file_arch`
    ADD COLUMN `UID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '内部ID' FIRST,
    CHANGE COLUMN `SID` `SID` INT(11) NULL COMMENT '归档前的ID' AFTER `UID`,
    DROP PRIMARY KEY,
    ADD PRIMARY KEY (`UID`);
ALTER TABLE `sys_stdtmp_file_01_arch`
    ADD COLUMN `UID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '内部ID' FIRST,
    CHANGE COLUMN `SID` `SID` INT(11) NULL COMMENT '归档前的ID' AFTER `UID`,
    DROP PRIMARY KEY,
    ADD PRIMARY KEY (`UID`);
ALTER TABLE `sys_stdtmp_file_02_arch`
    ADD COLUMN `UID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '内部ID' FIRST,
    CHANGE COLUMN `SID` `SID` INT(11) NULL COMMENT '归档前的ID' AFTER `UID`,
    DROP PRIMARY KEY,
    ADD PRIMARY KEY (`UID`);
ALTER TABLE `sys_stdtmp_file_03_arch`
    ADD COLUMN `UID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '内部ID' FIRST,
    CHANGE COLUMN `SID` `SID` INT(11) NULL COMMENT '归档前的ID' AFTER `UID`,
    DROP PRIMARY KEY,
    ADD PRIMARY KEY (`UID`);
ALTER TABLE `sys_stdtmp_file_04_arch`
    ADD COLUMN `UID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '内部ID' FIRST,
    CHANGE COLUMN `SID` `SID` INT(11) NULL COMMENT '归档前的ID' AFTER `UID`,
    DROP PRIMARY KEY,
    ADD PRIMARY KEY (`UID`);
ALTER TABLE `sys_stdtmp_file_06_arch`
    ADD COLUMN `UID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '内部ID' FIRST,
    CHANGE COLUMN `SID` `SID` INT(11) NULL COMMENT '归档前的ID' AFTER `UID`,
    DROP PRIMARY KEY,
    ADD PRIMARY KEY (`UID`);
ALTER TABLE `sys_stdtmp_file_07_arch`
    ADD COLUMN `UID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '内部ID' FIRST,
    CHANGE COLUMN `SID` `SID` INT(11) NULL COMMENT '归档前的ID' AFTER `UID`,
    DROP PRIMARY KEY,
    ADD PRIMARY KEY (`UID`);
ALTER TABLE `sys_stdtmp_file_08_arch`
    ADD COLUMN `UID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '内部ID' FIRST,
    CHANGE COLUMN `SID` `SID` INT(11) NULL COMMENT '归档前的ID' AFTER `UID`,
    DROP PRIMARY KEY,
    ADD PRIMARY KEY (`UID`);
ALTER TABLE `sys_stdtmp_file_09_arch`
    ADD COLUMN `UID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '内部ID' FIRST,
    CHANGE COLUMN `SID` `SID` INT(11) NULL COMMENT '归档前的ID' AFTER `UID`,
    DROP PRIMARY KEY,
    ADD PRIMARY KEY (`UID`);

DROP TABLE IF EXISTS `sys_template_text`;
CREATE TABLE `sys_template_text` (
    `SID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `R_TEMPLATE` INT(11) NOT NULL DEFAULT '0' COMMENT '所属模板',
    `P_TMPFILE` VARCHAR(32) NOT NULL COMMENT '模板文件类型代码',
    `R_SID` INT(11) NULL DEFAULT NULL COMMENT '对应记录ID',
    `C_CONTENT` LONGTEXT NULL COMMENT '内容',
    `R_CREATE` INT(11) NULL DEFAULT NULL COMMENT '创建人编号',
    `S_CREATE` VARCHAR(50) NULL DEFAULT NULL COMMENT '创建人',
    `T_CREATE` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
    `R_UPDATE` INT(11) NULL DEFAULT NULL COMMENT '更新人编号',
    `S_UPDATE` VARCHAR(50) NULL DEFAULT NULL COMMENT '更新人',
    `T_UPDATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `R_TENANT` INT(11) NULL DEFAULT NULL COMMENT '租户编号',
    `S_TENANT` VARCHAR(300) NULL DEFAULT NULL COMMENT '租户名称',
    `P_TENANT` CHAR(1) NULL DEFAULT NULL COMMENT '租户类型',
    `N_STATE` INT(11) NULL DEFAULT NULL COMMENT '状态',
    `B_DELETE` CHAR(1) NULL DEFAULT NULL COMMENT '删除标志',
    `N_INDEX` INT(11) NULL DEFAULT NULL COMMENT '排序',
    `N_VERSION` INT(11) NULL DEFAULT NULL COMMENT '版本',
    PRIMARY KEY (`SID`)
);

DROP TABLE IF EXISTS `ssm_template_text`;
CREATE TABLE `ssm_template_text` (
    `SID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    `R_TEMPLATE` INT(11) NOT NULL DEFAULT '0' COMMENT '所属模板',
    `P_PROFESSION` INT(11) NULL DEFAULT NULL COMMENT '企业专业编号',
    `P_TMPFILE` VARCHAR(32) NOT NULL COMMENT '模板文件类型代码',
    `R_SID` INT(11) NULL DEFAULT NULL COMMENT '对应记录ID',
    `C_CONTENT` LONGTEXT NULL COMMENT '内容',
    `R_CREATE` INT(11) NULL DEFAULT NULL COMMENT '创建人编号',
    `S_CREATE` VARCHAR(50) NULL DEFAULT NULL COMMENT '创建人',
    `T_CREATE` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
    `R_UPDATE` INT(11) NULL DEFAULT NULL COMMENT '更新人编号',
    `S_UPDATE` VARCHAR(50) NULL DEFAULT NULL COMMENT '更新人',
    `T_UPDATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `R_TENANT` INT(11) NULL DEFAULT NULL COMMENT '租户编号',
    `S_TENANT` VARCHAR(300) NULL DEFAULT NULL COMMENT '租户名称',
    `P_TENANT` CHAR(1) NULL DEFAULT NULL COMMENT '租户类型',
    `N_STATE` INT(11) NULL DEFAULT NULL COMMENT '状态',
    `B_DELETE` CHAR(1) NULL DEFAULT NULL COMMENT '删除标志',
    `N_INDEX` INT(11) NULL DEFAULT NULL COMMENT '排序',
    `N_VERSION` INT(11) NULL DEFAULT NULL COMMENT '版本',
    PRIMARY KEY (`SID`)
);

DROP TABLE IF EXISTS `sys_template_text_arch`;
CREATE TABLE `sys_template_text_arch` (
    `UID` INT(11) NOT NULL AUTO_INCREMENT,
    `SID` INT(11) NOT NULL COMMENT '原始主键',
    `R_TEMPLATE` INT(11) NOT NULL DEFAULT '0' COMMENT '所属模板',
    `P_TMPFILE` VARCHAR(32) NULL DEFAULT NULL COMMENT '模板类型编号',
    `R_SID` INT(11) NULL DEFAULT NULL COMMENT '对应记录ID',
    `C_CONTENT` LONGTEXT NULL COMMENT '内容',
    `R_CREATE` INT(11) NULL DEFAULT NULL COMMENT '创建人编号',
    `S_CREATE` VARCHAR(50) NULL DEFAULT NULL COMMENT '创建人',
    `T_CREATE` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
    `R_UPDATE` INT(11) NULL DEFAULT NULL COMMENT '更新人编号',
    `S_UPDATE` VARCHAR(50) NULL DEFAULT NULL COMMENT '更新人',
    `T_UPDATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `R_TENANT` INT(11) NULL DEFAULT NULL COMMENT '租户编号',
    `S_TENANT` VARCHAR(300) NULL DEFAULT NULL COMMENT '租户名称',
    `P_TENANT` CHAR(1) NULL DEFAULT NULL COMMENT '租户类型',
    `N_STATE` INT(11) NULL DEFAULT NULL COMMENT '状态',
    `B_DELETE` CHAR(1) NULL DEFAULT NULL COMMENT '删除标志',
    `N_INDEX` INT(11) NULL DEFAULT NULL COMMENT '排序',
    `N_VERSION` INT(11) NULL DEFAULT NULL COMMENT '版本',
    PRIMARY KEY (`UID`)
);

DROP TABLE IF EXISTS `ssm_template_text_arch`;
CREATE TABLE `ssm_template_text_arch` (
    `UID` INT(11) NOT NULL AUTO_INCREMENT,
    `SID` INT(11) NOT NULL COMMENT '原始主键',
    `R_TEMPLATE` INT(11) NOT NULL DEFAULT '0' COMMENT '所属模板',
    `P_PROFESSION` INT(11) NULL DEFAULT NULL COMMENT '企业专业编号',
    `P_TMPFILE` VARCHAR(32) NULL DEFAULT NULL COMMENT '模板类型编号',
    `R_SID` INT(11) NULL DEFAULT NULL COMMENT '对应记录ID',
    `C_CONTENT` LONGTEXT NULL COMMENT '内容',
    `R_CREATE` INT(11) NULL DEFAULT NULL COMMENT '创建人编号',
    `S_CREATE` VARCHAR(50) NULL DEFAULT NULL COMMENT '创建人',
    `T_CREATE` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
    `R_UPDATE` INT(11) NULL DEFAULT NULL COMMENT '更新人编号',
    `S_UPDATE` VARCHAR(50) NULL DEFAULT NULL COMMENT '更新人',
    `T_UPDATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `R_TENANT` INT(11) NULL DEFAULT NULL COMMENT '租户编号',
    `S_TENANT` VARCHAR(300) NULL DEFAULT NULL COMMENT '租户名称',
    `P_TENANT` CHAR(1) NULL DEFAULT NULL COMMENT '租户类型',
    `N_STATE` INT(11) NULL DEFAULT NULL COMMENT '状态',
    `B_DELETE` CHAR(1) NULL DEFAULT NULL COMMENT '删除标志',
    `N_INDEX` INT(11) NULL DEFAULT NULL COMMENT '排序',
    `N_VERSION` INT(11) NULL DEFAULT NULL COMMENT '版本',
    PRIMARY KEY (`UID`)
);

ALTER TABLE `sys_stdtmp_file_01`
ADD COLUMN `R_TEMPLATE` INT(11) NULL DEFAULT NULL COMMENT '所属模板' AFTER `SID`;
ALTER TABLE `sys_stdtmp_file_02`
ADD COLUMN `R_TEMPLATE` INT(11) NULL DEFAULT NULL COMMENT '所属模板' AFTER `SID`;
ALTER TABLE `sys_stdtmp_file_03`
ADD COLUMN `R_TEMPLATE` INT(11) NULL DEFAULT NULL COMMENT '所属模板' AFTER `SID`;
ALTER TABLE `sys_stdtmp_file_04`
ADD COLUMN `R_TEMPLATE` INT(11) NULL DEFAULT NULL COMMENT '所属模板' AFTER `SID`;
ALTER TABLE `sys_stdtmp_file_06`
ADD COLUMN `R_TEMPLATE` INT(11) NULL DEFAULT NULL COMMENT '所属模板' AFTER `SID`;
ALTER TABLE `sys_stdtmp_file_07`
ADD COLUMN `R_TEMPLATE` INT(11) NULL DEFAULT NULL COMMENT '所属模板' AFTER `SID`;
ALTER TABLE `sys_stdtmp_file_08`
ADD COLUMN `R_TEMPLATE` INT(11) NULL DEFAULT NULL COMMENT '所属模板' AFTER `SID`;
ALTER TABLE `sys_stdtmp_file_09`
ADD COLUMN `R_TEMPLATE` INT(11) NULL DEFAULT NULL COMMENT '所属模板' AFTER `SID`;

ALTER TABLE `sys_stdtmp_file_01_arch`
ADD COLUMN `R_TEMPLATE` INT(11) NULL DEFAULT NULL COMMENT '所属模板' AFTER `SID`;
ALTER TABLE `sys_stdtmp_file_02_arch`
ADD COLUMN `R_TEMPLATE` INT(11) NULL DEFAULT NULL COMMENT '所属模板' AFTER `SID`;
ALTER TABLE `sys_stdtmp_file_03_arch`
ADD COLUMN `R_TEMPLATE` INT(11) NULL DEFAULT NULL COMMENT '所属模板' AFTER `SID`;
ALTER TABLE `sys_stdtmp_file_04_arch`
ADD COLUMN `R_TEMPLATE` INT(11) NULL DEFAULT NULL COMMENT '所属模板' AFTER `SID`;
ALTER TABLE `sys_stdtmp_file_06_arch`
ADD COLUMN `R_TEMPLATE` INT(11) NULL DEFAULT NULL COMMENT '所属模板' AFTER `SID`;
ALTER TABLE `sys_stdtmp_file_07_arch`
ADD COLUMN `R_TEMPLATE` INT(11) NULL DEFAULT NULL COMMENT '所属模板' AFTER `SID`;
ALTER TABLE `sys_stdtmp_file_08_arch`
ADD COLUMN `R_TEMPLATE` INT(11) NULL DEFAULT NULL COMMENT '所属模板' AFTER `SID`;
ALTER TABLE `sys_stdtmp_file_09_arch`
ADD COLUMN `R_TEMPLATE` INT(11) NULL DEFAULT NULL COMMENT '所属模板' AFTER `SID`;


-- ============================================
delete from sys_template_text;
delete from ssm_template_text;

-- sys_stdtmp_file_01
update sys_stdtmp_file_01 a
set R_TEMPLATE = (
    select R_TEMPLATE from sys_stdtmp_file b where a.R_TMPFILE = b.sid
);
delete from sys_stdtmp_file_01 where R_TEMPLATE is NULL;
insert into sys_template_text(R_TEMPLATE, P_TMPFILE,R_SID,C_CONTENT,R_CREATE,S_CREATE,T_CREATE,R_UPDATE,S_UPDATE,T_UPDATE,R_TENANT,S_TENANT,P_TENANT,N_STATE,B_DELETE,N_INDEX,N_VERSION)
    select b.R_TEMPLATE,substr(A.R_TABLE, 17),A.R_SID,A.C_CONTENT,A.R_CREATE,A.S_CREATE,A.T_CREATE,A.R_UPDATE,A.S_UPDATE,A.T_UPDATE,A.R_TENANT,A.S_TENANT,A.P_TENANT,A.N_STATE,A.B_DELETE,A.N_INDEX,A.N_VERSION
    from sys_attach_text a
        inner join sys_stdtmp_file_01 b on a.R_SID = B.SID
    where A.R_TABLE like 'SYS_STDTMP_FILE_01';

-- sys_stdtmp_file_02
update sys_stdtmp_file_02 a
set R_TEMPLATE = (
    select R_TEMPLATE from sys_stdtmp_file b where a.R_TMPFILE = b.sid
);
delete from sys_stdtmp_file_02 where R_TEMPLATE is NULL;
insert into sys_template_text(R_TEMPLATE, P_TMPFILE,R_SID,C_CONTENT,R_CREATE,S_CREATE,T_CREATE,R_UPDATE,S_UPDATE,T_UPDATE,R_TENANT,S_TENANT,P_TENANT,N_STATE,B_DELETE,N_INDEX,N_VERSION)
    select b.R_TEMPLATE,substr(A.R_TABLE, 17),A.R_SID,A.C_CONTENT,A.R_CREATE,A.S_CREATE,A.T_CREATE,A.R_UPDATE,A.S_UPDATE,A.T_UPDATE,A.R_TENANT,A.S_TENANT,A.P_TENANT,A.N_STATE,A.B_DELETE,A.N_INDEX,A.N_VERSION
    from sys_attach_text a
        inner join sys_stdtmp_file_02 b on a.R_SID = B.SID
    where A.R_TABLE like 'SYS_STDTMP_FILE_02';

-- sys_stdtmp_file_03
update sys_stdtmp_file_03 a
set R_TEMPLATE = (
    select R_TEMPLATE from sys_stdtmp_file b where a.R_TMPFILE = b.sid
);
delete from sys_stdtmp_file_03 where R_TEMPLATE is NULL;
insert into sys_template_text(R_TEMPLATE, P_TMPFILE,R_SID,C_CONTENT,R_CREATE,S_CREATE,T_CREATE,R_UPDATE,S_UPDATE,T_UPDATE,R_TENANT,S_TENANT,P_TENANT,N_STATE,B_DELETE,N_INDEX,N_VERSION)
    select b.R_TEMPLATE,substr(A.R_TABLE, 17),A.R_SID,A.C_CONTENT,A.R_CREATE,A.S_CREATE,A.T_CREATE,A.R_UPDATE,A.S_UPDATE,A.T_UPDATE,A.R_TENANT,A.S_TENANT,A.P_TENANT,A.N_STATE,A.B_DELETE,A.N_INDEX,A.N_VERSION
    from sys_attach_text a
        inner join sys_stdtmp_file_03 b on a.R_SID = B.SID
    where A.R_TABLE like 'SYS_STDTMP_FILE_03';

-- sys_stdtmp_file_04
update sys_stdtmp_file_04 a
set R_TEMPLATE = (
    select R_TEMPLATE from sys_stdtmp_file b where a.R_TMPFILE = b.sid
);
delete from sys_stdtmp_file_04 where R_TEMPLATE is NULL;
insert into sys_template_text(R_TEMPLATE, P_TMPFILE,R_SID,C_CONTENT,R_CREATE,S_CREATE,T_CREATE,R_UPDATE,S_UPDATE,T_UPDATE,R_TENANT,S_TENANT,P_TENANT,N_STATE,B_DELETE,N_INDEX,N_VERSION)
    select b.R_TEMPLATE,substr(A.R_TABLE, 17),A.R_SID,A.C_CONTENT,A.R_CREATE,A.S_CREATE,A.T_CREATE,A.R_UPDATE,A.S_UPDATE,A.T_UPDATE,A.R_TENANT,A.S_TENANT,A.P_TENANT,A.N_STATE,A.B_DELETE,A.N_INDEX,A.N_VERSION
    from sys_attach_text a
        inner join sys_stdtmp_file_04 b on a.R_SID = B.SID
    where A.R_TABLE like 'SYS_STDTMP_FILE_04';

-- sys_stdtmp_file_06
update sys_stdtmp_file_06 a
set R_TEMPLATE = (
    select R_TEMPLATE from sys_stdtmp_file b where a.R_TMPFILE = b.sid
);
delete from sys_stdtmp_file_06 where R_TEMPLATE is NULL;
insert into sys_template_text(R_TEMPLATE, P_TMPFILE,R_SID,C_CONTENT,R_CREATE,S_CREATE,T_CREATE,R_UPDATE,S_UPDATE,T_UPDATE,R_TENANT,S_TENANT,P_TENANT,N_STATE,B_DELETE,N_INDEX,N_VERSION)
    select b.R_TEMPLATE,substr(A.R_TABLE, 17),A.R_SID,A.C_CONTENT,A.R_CREATE,A.S_CREATE,A.T_CREATE,A.R_UPDATE,A.S_UPDATE,A.T_UPDATE,A.R_TENANT,A.S_TENANT,A.P_TENANT,A.N_STATE,A.B_DELETE,A.N_INDEX,A.N_VERSION
    from sys_attach_text a
        inner join sys_stdtmp_file_06 b on a.R_SID = B.SID
    where A.R_TABLE like 'SYS_STDTMP_FILE_06';

-- sys_stdtmp_file_07
update sys_stdtmp_file_07 a
set R_TEMPLATE = (
    select R_TEMPLATE from sys_stdtmp_file b where a.R_TMPFILE = b.sid
);
delete from sys_stdtmp_file_07 where R_TEMPLATE is NULL;
insert into sys_template_text(R_TEMPLATE, P_TMPFILE,R_SID,C_CONTENT,R_CREATE,S_CREATE,T_CREATE,R_UPDATE,S_UPDATE,T_UPDATE,R_TENANT,S_TENANT,P_TENANT,N_STATE,B_DELETE,N_INDEX,N_VERSION)
    select b.R_TEMPLATE,substr(A.R_TABLE, 17),A.R_SID,A.C_CONTENT,A.R_CREATE,A.S_CREATE,A.T_CREATE,A.R_UPDATE,A.S_UPDATE,A.T_UPDATE,A.R_TENANT,A.S_TENANT,A.P_TENANT,A.N_STATE,A.B_DELETE,A.N_INDEX,A.N_VERSION
    from sys_attach_text a
        inner join sys_stdtmp_file_07 b on a.R_SID = B.SID
    where A.R_TABLE like 'SYS_STDTMP_FILE_07';

-- sys_stdtmp_file_08
update sys_stdtmp_file_08 a
set R_TEMPLATE = (
    select R_TEMPLATE from sys_stdtmp_file b where a.R_TMPFILE = b.sid
);
delete from sys_stdtmp_file_08 where R_TEMPLATE is NULL;
insert into sys_template_text(R_TEMPLATE, P_TMPFILE,R_SID,C_CONTENT,R_CREATE,S_CREATE,T_CREATE,R_UPDATE,S_UPDATE,T_UPDATE,R_TENANT,S_TENANT,P_TENANT,N_STATE,B_DELETE,N_INDEX,N_VERSION)
    select b.R_TEMPLATE,substr(A.R_TABLE, 17),A.R_SID,A.C_CONTENT,A.R_CREATE,A.S_CREATE,A.T_CREATE,A.R_UPDATE,A.S_UPDATE,A.T_UPDATE,A.R_TENANT,A.S_TENANT,A.P_TENANT,A.N_STATE,A.B_DELETE,A.N_INDEX,A.N_VERSION
    from sys_attach_text a
        inner join sys_stdtmp_file_08 b on a.R_SID = B.SID
    where A.R_TABLE like 'SYS_STDTMP_FILE_08';

-- sys_stdtmp_file_09
update sys_stdtmp_file_09 a
set R_TEMPLATE = (
    select R_TEMPLATE from sys_stdtmp_file b where a.R_TMPFILE = b.sid
);
delete from sys_stdtmp_file_09 where R_TEMPLATE is NULL;
insert into sys_template_text(R_TEMPLATE, P_TMPFILE,R_SID,C_CONTENT,R_CREATE,S_CREATE,T_CREATE,R_UPDATE,S_UPDATE,T_UPDATE,R_TENANT,S_TENANT,P_TENANT,N_STATE,B_DELETE,N_INDEX,N_VERSION)
    select b.R_TEMPLATE,substr(A.R_TABLE, 17),A.R_SID,A.C_CONTENT,A.R_CREATE,A.S_CREATE,A.T_CREATE,A.R_UPDATE,A.S_UPDATE,A.T_UPDATE,A.R_TENANT,A.S_TENANT,A.P_TENANT,A.N_STATE,A.B_DELETE,A.N_INDEX,A.N_VERSION
    from sys_attach_text a
        inner join sys_stdtmp_file_09 b on a.R_SID = B.SID
    where A.R_TABLE like 'SYS_STDTMP_FILE_09';
