-- 评审人员表:
DROP TABLE IF EXISTS SSM_REVIEWER;
CREATE TABLE SSM_REVIEWER
(
  `SID`             INT(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `C_NAME`          VARCHAR(100) COMMENT '姓名',
  `C_SEX`           CHAR(1) COMMENT '性别',
  `T_BIRTH`         DATE COMMENT '出生日期',
  `C_DEPT`          VARCHAR(200) COMMENT '工作单位及部门',
  `C_POSITION`      VARCHAR(100) COMMENT '职务',
  `C_TECHNOLOGY`    VARCHAR(100) COMMENT '专业技术职务',
  `C_ADDR`          VARCHAR(500) COMMENT '通讯地址',
  `C_ZIP`           VARCHAR(10) COMMENT '邮编',
  `C_MOBILE`        VARCHAR(50) COMMENT '移动电话',
  `C_EMAIL`         VARCHAR(50) COMMENT '电子邮件',
  `C_CARD`          VARCHAR(50) COMMENT '身份证',
  `C_CERTIFICATENO` VARCHAR(50) COMMENT '聘请证书编号',
  `C_INDUSTRY`      VARCHAR(100) COMMENT '行业',
  `C_PROFESSION`    VARCHAR(100) COMMENT '专业',
  `C_SCHOOL`        VARCHAR(100) COMMENT '毕业学校',
  `C_EDUCATION`     VARCHAR(50) COMMENT '学历',
  `C_DEGREE`        VARCHAR(50) COMMENT '学位',
  `C_MAJOR`         VARCHAR(50) COMMENT '所学专业',
  `C_ENGPROANDAGE`  VARCHAR(100) COMMENT '现从事专业及年限',
  `C_SUMMARY`       VARCHAR(1000) COMMENT '工作简历及主要成绩',
  `P_CLASSWORKER`   VARCHAR(32) COMMENT '人员类别编号',
  `S_CLASSWORKER`   VARCHAR(100) COMMENT '人员类别',
  `R_CREATE`        INT(11) COMMENT '创建人编号',
  `S_CREATE`        VARCHAR(50) COMMENT '创建人',
  `T_CREATE`        DATETIME COMMENT '创建时间',
  `R_UPDATE`        INT(11) COMMENT '更新人编号',
  `S_UPDATE`        VARCHAR(50) COMMENT '更新人',
  `T_UPDATE`        TIMESTAMP COMMENT '更新时间',
  `R_TENANT`        INT(11) COMMENT '租户编号',
  `S_TENANT`        VARCHAR(300) COMMENT '租户名称',
  `P_TENANT`        CHAR(1) COMMENT '租户类型',
  `N_STATE`         INT COMMENT '状态',
  `B_DELETE`        CHAR(1) COMMENT '删除标志',
  `N_INDEX`         INT COMMENT '排序',
  `N_VERSION`       INT COMMENT '版本',
  PRIMARY KEY (`SID`)
);