/*企业视图*/
CREATE OR REPLACE VIEW V_TENANT_E AS
	SELECT t1.SID,t1.C_NAME,t1.C_CODE,
	t1.C_ADDR,t1.C_CONTACT,t1.C_TEL,
	t1.N_STATE,t1.P_PROVINCE,t1.P_CITY,t1.P_COUNTY,
	t2.R_PROFESSION,t2.S_PROFESSION C_NAME_PRO,
	t3.C_NAME C_NAME_IND
	FROM SYS_TENANT_E t1
	LEFT JOIN sys_tenant_e_profession t2 ON t1.sid=t2.R_TENANT
	LEFT JOIN sys_industry t3 ON t1.R_INDUSTRY=t3.SID	
	ORDER BY t1.N_INDEX,t1.SID;