DELIMITER $$

/*自评完成处理*/
DROP PROCEDURE IF EXISTS `P_GRADE_COMPLETE_E`$$
CREATE PROCEDURE P_GRADE_COMPLETE_E(IN IN_SID INT)  
    BEGIN
	/*更改状态*/
	UPDATE SSM_GRADE_E_M SET N_STATE=3 WHERE SID=IN_SID;

	/*从自评报告模板生成*/
	INSERT INTO SSM_GRADE_REPORT(R_SID,C_CONTENT)
	SELECT IN_SID,T3.C_CONTENT FROM 
	SSM_GRADE_E_M T1
	LEFT JOIN SYS_TENANT_E_PROFESSION T2 ON T1.R_TENANT=T2.R_TENANT
	LEFT JOIN SSM_GRADE_REPORT_TMP T3 ON T3.P_PROFESSION=T2.P_PROFESSION
	WHERE NOT EXISTS(SELECT 1 FROM SSM_GRADE_REPORT WHERE R_SID=IN_SID);
    END$$

DROP PROCEDURE IF EXISTS `P_GRADE_COMPLETE_E`$$
CREATE PROCEDURE P_GRADE_COMPLETE_E(IN IN_SID INT)  
    BEGIN
	/*更改状态*/
	UPDATE SSM_GRADE_E_M SET N_STATE=3 WHERE SID=IN_SID;

	/*从自评报告模板生成*/
	INSERT INTO SYS_ATTACH_TEXT(R_TABLE,R_SID,R_FIELD,C_CONTENT,R_TENANT,S_TENANT,P_TENANT)
	SELECT 'SSM_GRADE_REPORT',IN_SID,'CONTENT',T3.C_CONTENT,T1.R_TENANT,T1.S_TENANT,T1.P_TENANT FROM 
	SSM_GRADE_E_M T1
	LEFT JOIN SYS_TENANT_E_PROFESSION T2 ON T1.R_TENANT=T2.R_TENANT
	LEFT JOIN SSM_GRADE_REPORT_TMP T3 ON T3.P_PROFESSION=T2.P_PROFESSION
	WHERE NOT EXISTS(SELECT 1 FROM SYS_ATTACH_TEXT WHERE R_SID=IN_SID AND R_TABLE='SSM_GRADE_REPORT' AND R_FIELD='CONTENT');

    END$$

DELIMITER ;