-- 删除模板文件字段调整
ALTER TABLE `sys_stdtmp_file`
DROP COLUMN `R_TMPFILE`;

ALTER TABLE `sys_stdtmp_file_01`
ADD COLUMN `R_TMPFILE`  int(11) NOT NULL AFTER `SID`;

ALTER TABLE `sys_stdtmp_file_02`
ADD COLUMN `R_TMPFILE`  int(11) NOT NULL AFTER `SID`;

ALTER TABLE `sys_stdtmp_file_03`
ADD COLUMN `R_TMPFILE`  int(11) NOT NULL AFTER `SID`;

ALTER TABLE `sys_stdtmp_file_04`
ADD COLUMN `R_TMPFILE`  int(11) NOT NULL AFTER `SID`;

ALTER TABLE `sys_stdtmp_file_05`
ADD COLUMN `R_TMPFILE`  int(11) NOT NULL AFTER `SID`;

ALTER TABLE `sys_stdtmp_file_06`
ADD COLUMN `R_TMPFILE`  int(11) NOT NULL AFTER `SID`;


ALTER TABLE `ssm_stdtmp_file`
DROP COLUMN `R_TMPFILE`;

ALTER TABLE `ssm_stdtmp_file_01`
ADD COLUMN `R_TMPFILE`  int(11) NOT NULL AFTER `SID`;

ALTER TABLE `ssm_stdtmp_file_02`
ADD COLUMN `R_TMPFILE`  int(11) NOT NULL AFTER `SID`;

ALTER TABLE `ssm_stdtmp_file_03`
ADD COLUMN `R_TMPFILE`  int(11) NOT NULL AFTER `SID`;

ALTER TABLE `ssm_stdtmp_file_04`
ADD COLUMN `R_TMPFILE`  int(11) NOT NULL AFTER `SID`;

ALTER TABLE `ssm_stdtmp_file_05`
ADD COLUMN `R_TMPFILE`  int(11) NOT NULL AFTER `SID`;

ALTER TABLE `ssm_stdtmp_file_06`
ADD COLUMN `R_TMPFILE`  int(11) NOT NULL AFTER `SID`;



-- 特种作业人员持证登记表模板配置:

DROP TABLE IF EXISTS SYS_STDTMP_FILE_07;
CREATE TABLE SYS_STDTMP_FILE_07
(

	`SID`		INT(11) 	NOT NULL auto_increment COMMENT '自增主键',
	`R_TMPFILE`			INT(11)	 NOT NULL COMMENT '模板ID',
	`C_NAME`			VARCHAR(300)	 COMMENT '姓名',
	`P_SEX`			VARCHAR(32)	 COMMENT '性别',
	`S_SEX`			VARCHAR(100)	 COMMENT '性别',
	`C_CARD`			VARCHAR(30)	 COMMENT '身份证号码',
	`C_DEPT`			VARCHAR(200)	 COMMENT '所在部门',
	`C_WORKTYPE`			VARCHAR(100)	 COMMENT '工种',
	`C_AUTH`			VARCHAR(300)	 COMMENT '发证机关',
	`T_CERT_GET`			DATE	 COMMENT '取证时间',
	`C_CERT`			VARCHAR(100)	 COMMENT '证书编号',
	`T_CERT_REVIEW`			DATE	 COMMENT '复审时间',
	`R_CREATE`			INT(11)	 COMMENT '创建人编号',
	`S_CREATE`			VARCHAR(50)	 COMMENT '创建人',
	`T_CREATE`			DATETIME	 COMMENT '创建时间',
	`R_UPDATE`			INT(11)	 COMMENT '更新人编号',
	`S_UPDATE`			VARCHAR(50)	 COMMENT '更新人',
	`T_UPDATE`			TIMESTAMP	 COMMENT '更新时间',
	`R_TENANT`			INT(11)	 COMMENT '租户编号',
	`S_TENANT`			VARCHAR(300)	 COMMENT '租户名称',
	`P_TENANT`			CHAR(1)	 COMMENT '租户类型',
	`N_STATE`			INT	 COMMENT '状态',
	`B_DELETE`			CHAR(1)	 COMMENT '删除标志',
	`N_INDEX`			INT	 COMMENT '排序',
	`N_VERSION`			INT	 COMMENT '版本',
	PRIMARY KEY  (`SID`)
);


-- 特种设备台账及定期检验记录模板配置:

DROP TABLE IF EXISTS SYS_STDTMP_FILE_08;
CREATE TABLE SYS_STDTMP_FILE_08
(

	`SID`		INT(11) 	NOT NULL auto_increment COMMENT '自增主键',
	`R_TMPFILE`			INT(11)	 NOT NULL COMMENT '模板ID',
	`C_NAME`			VARCHAR(300)	 COMMENT '设备名称',
	`C_NO_REG`			VARCHAR(100)	 COMMENT '登记证号',
	`C_SPEC`			VARCHAR(100)	 COMMENT '规格/型号',
	`C_MAKE_UNIT`			VARCHAR(100)	 COMMENT '制造单位',
	`C_NO_FACTORY`			VARCHAR(100)	 COMMENT '出厂编号',
	`C_DEPT`			VARCHAR(200)	 COMMENT '使用部门',
	`T_TEST_LAST`			DATE	 COMMENT '最新检验日期',
	`C_NO_REP`			VARCHAR(100)	 COMMENT '检验报告编号',
	`T_TEST_NEXT`			DATE	 COMMENT '下次检验日期',
	`C_TEST_CON`			VARCHAR(3000)	 COMMENT '检验结论',
	`C_TEST_UNIT`			VARCHAR(200)	 COMMENT '检验单位',
	`R_CREATE`			INT(11)	 COMMENT '创建人编号',
	`S_CREATE`			VARCHAR(50)	 COMMENT '创建人',
	`T_CREATE`			DATETIME	 COMMENT '创建时间',
	`R_UPDATE`			INT(11)	 COMMENT '更新人编号',
	`S_UPDATE`			VARCHAR(50)	 COMMENT '更新人',
	`T_UPDATE`			TIMESTAMP	 COMMENT '更新时间',
	`R_TENANT`			INT(11)	 COMMENT '租户编号',
	`S_TENANT`			VARCHAR(300)	 COMMENT '租户名称',
	`P_TENANT`			CHAR(1)	 COMMENT '租户类型',
	`N_STATE`			INT	 COMMENT '状态',
	`B_DELETE`			CHAR(1)	 COMMENT '删除标志',
	`N_INDEX`			INT	 COMMENT '排序',
	`N_VERSION`			INT	 COMMENT '版本',
	PRIMARY KEY  (`SID`)
);


-- 安全附件定期检查检验记录模板配置:

DROP TABLE IF EXISTS SYS_STDTMP_FILE_09;
CREATE TABLE SYS_STDTMP_FILE_09
(

	`SID`		INT(11) 	NOT NULL auto_increment COMMENT '自增主键',
	`R_TMPFILE`			INT(11)	 NOT NULL COMMENT '模板ID',
	`C_NAME`			VARCHAR(300)	 COMMENT '安全附件名称',
	`C_SPEC`			VARCHAR(100)	 COMMENT '型号',
	`C_NO_FACTORY`			VARCHAR(100)	 COMMENT '出厂编号',
	`C_POSITION`			VARCHAR(500)	 COMMENT '所属特种设备安装位置',
	`T_TEST_LAST`			DATE	 COMMENT '检验日期',
	`T_TEST_NEXT`			DATE	 COMMENT '下次检验日期',
	`C_NO_REP`			VARCHAR(100)	 COMMENT '检验报告编号',
	`C_TEST_CON`			VARCHAR(3000)	 COMMENT '检验结论',
	`C_TEST_UNIT`			VARCHAR(200)	 COMMENT '检验单位',
	`R_CREATE`			INT(11)	 COMMENT '创建人编号',
	`S_CREATE`			VARCHAR(50)	 COMMENT '创建人',
	`T_CREATE`			DATETIME	 COMMENT '创建时间',
	`R_UPDATE`			INT(11)	 COMMENT '更新人编号',
	`S_UPDATE`			VARCHAR(50)	 COMMENT '更新人',
	`T_UPDATE`			TIMESTAMP	 COMMENT '更新时间',
	`R_TENANT`			INT(11)	 COMMENT '租户编号',
	`S_TENANT`			VARCHAR(300)	 COMMENT '租户名称',
	`P_TENANT`			CHAR(1)	 COMMENT '租户类型',
	`N_STATE`			INT	 COMMENT '状态',
	`B_DELETE`			CHAR(1)	 COMMENT '删除标志',
	`N_INDEX`			INT	 COMMENT '排序',
	`N_VERSION`			INT	 COMMENT '版本',
	PRIMARY KEY  (`SID`)
);

-- 特种作业人员持证登记表模板配置:
DROP TABLE IF EXISTS SSM_STDTMP_FILE_07;
CREATE TABLE SSM_STDTMP_FILE_07
(

	`SID`		INT(11) 	NOT NULL auto_increment COMMENT '自增主键',
	`R_TMPFILE`			INT(11)	 NOT NULL COMMENT '模板ID',
	`C_NAME`			VARCHAR(300)	 COMMENT '姓名',
	`P_SEX`			VARCHAR(32)	 COMMENT '性别',
	`S_SEX`			VARCHAR(100)	 COMMENT '性别',
	`C_CARD`			VARCHAR(30)	 COMMENT '身份证号码',
	`C_DEPT`			VARCHAR(200)	 COMMENT '所在部门',
	`C_WORKTYPE`			VARCHAR(100)	 COMMENT '工种',
	`C_AUTH`			VARCHAR(300)	 COMMENT '发证机关',
	`T_CERT_GET`			DATE	 COMMENT '取证时间',
	`C_CERT`			VARCHAR(100)	 COMMENT '证书编号',
	`T_CERT_REVIEW`			DATE	 COMMENT '复审时间',
	`R_CREATE`			INT(11)	 COMMENT '创建人编号',
	`S_CREATE`			VARCHAR(50)	 COMMENT '创建人',
	`T_CREATE`			DATETIME	 COMMENT '创建时间',
	`R_UPDATE`			INT(11)	 COMMENT '更新人编号',
	`S_UPDATE`			VARCHAR(50)	 COMMENT '更新人',
	`T_UPDATE`			TIMESTAMP	 COMMENT '更新时间',
	`R_TENANT`			INT(11)	 COMMENT '租户编号',
	`S_TENANT`			VARCHAR(300)	 COMMENT '租户名称',
	`P_TENANT`			CHAR(1)	 COMMENT '租户类型',
	`N_STATE`			INT	 COMMENT '状态',
	`B_DELETE`			CHAR(1)	 COMMENT '删除标志',
	`N_INDEX`			INT	 COMMENT '排序',
	`N_VERSION`			INT	 COMMENT '版本',
	PRIMARY KEY  (`SID`)
);


-- 特种设备台账及定期检验记录模板配置:
DROP TABLE IF EXISTS SSM_STDTMP_FILE_08;
CREATE TABLE SSM_STDTMP_FILE_08
(

	`SID`		INT(11) 	NOT NULL auto_increment COMMENT '自增主键',
	`R_TMPFILE`			INT(11)	 NOT NULL COMMENT '模板ID',
	`C_NAME`			VARCHAR(300)	 COMMENT '设备名称',
	`C_NO_REG`			VARCHAR(100)	 COMMENT '登记证号',
	`C_SPEC`			VARCHAR(100)	 COMMENT '规格/型号',
	`C_MAKE_UNIT`			VARCHAR(100)	 COMMENT '制造单位',
	`C_NO_FACTORY`			VARCHAR(100)	 COMMENT '出厂编号',
	`C_DEPT`			VARCHAR(200)	 COMMENT '使用部门',
	`T_TEST_LAST`			DATE	 COMMENT '最新检验日期',
	`C_NO_REP`			VARCHAR(100)	 COMMENT '检验报告编号',
	`T_TEST_NEXT`			DATE	 COMMENT '下次检验日期',
	`C_TEST_CON`			VARCHAR(3000)	 COMMENT '检验结论',
	`C_TEST_UNIT`			VARCHAR(200)	 COMMENT '检验单位',
	`R_CREATE`			INT(11)	 COMMENT '创建人编号',
	`S_CREATE`			VARCHAR(50)	 COMMENT '创建人',
	`T_CREATE`			DATETIME	 COMMENT '创建时间',
	`R_UPDATE`			INT(11)	 COMMENT '更新人编号',
	`S_UPDATE`			VARCHAR(50)	 COMMENT '更新人',
	`T_UPDATE`			TIMESTAMP	 COMMENT '更新时间',
	`R_TENANT`			INT(11)	 COMMENT '租户编号',
	`S_TENANT`			VARCHAR(300)	 COMMENT '租户名称',
	`P_TENANT`			CHAR(1)	 COMMENT '租户类型',
	`N_STATE`			INT	 COMMENT '状态',
	`B_DELETE`			CHAR(1)	 COMMENT '删除标志',
	`N_INDEX`			INT	 COMMENT '排序',
	`N_VERSION`			INT	 COMMENT '版本',
	PRIMARY KEY  (`SID`)
);


-- 安全附件定期检查检验记录模板配置:
DROP TABLE IF EXISTS SSM_STDTMP_FILE_09;
CREATE TABLE SSM_STDTMP_FILE_09
(

	`SID`		INT(11) 	NOT NULL auto_increment COMMENT '自增主键',
	`R_TMPFILE`			INT(11)	 NOT NULL COMMENT '模板ID',
	`C_NAME`			VARCHAR(300)	 COMMENT '安全附件名称',
	`C_SPEC`			VARCHAR(100)	 COMMENT '型号',
	`C_NO_FACTORY`			VARCHAR(100)	 COMMENT '出厂编号',
	`C_POSITION`			VARCHAR(500)	 COMMENT '所属特种设备安装位置',
	`T_TEST_LAST`			DATE	 COMMENT '检验日期',
	`T_TEST_NEXT`			DATE	 COMMENT '下次检验日期',
	`C_NO_REP`			VARCHAR(100)	 COMMENT '检验报告编号',
	`C_TEST_CON`			VARCHAR(3000)	 COMMENT '检验结论',
	`C_TEST_UNIT`			VARCHAR(200)	 COMMENT '检验单位',
	`R_CREATE`			INT(11)	 COMMENT '创建人编号',
	`S_CREATE`			VARCHAR(50)	 COMMENT '创建人',
	`T_CREATE`			DATETIME	 COMMENT '创建时间',
	`R_UPDATE`			INT(11)	 COMMENT '更新人编号',
	`S_UPDATE`			VARCHAR(50)	 COMMENT '更新人',
	`T_UPDATE`			TIMESTAMP	 COMMENT '更新时间',
	`R_TENANT`			INT(11)	 COMMENT '租户编号',
	`S_TENANT`			VARCHAR(300)	 COMMENT '租户名称',
	`P_TENANT`			CHAR(1)	 COMMENT '租户类型',
	`N_STATE`			INT	 COMMENT '状态',
	`B_DELETE`			CHAR(1)	 COMMENT '删除标志',
	`N_INDEX`			INT	 COMMENT '排序',
	`N_VERSION`			INT	 COMMENT '版本',
	PRIMARY KEY  (`SID`)
);


-- 隐患汇总登记台帐模板配置:
DROP TABLE IF EXISTS SYS_STDTMP_FILE_06_ITEM;
DROP TABLE IF EXISTS SYS_STDTMP_FILE_06;
CREATE TABLE SYS_STDTMP_FILE_06
(

	`SID`		INT(11) 	NOT NULL auto_increment COMMENT '自增主键',
	`R_TMPFILE`  int(11) NOT NULL,
	`C_NAME`			VARCHAR(300)	 COMMENT '存在问题',
	`C_EXAMINER`			VARCHAR(300)	 COMMENT '检查人',
	`T_EXAMINE`			DATE	 COMMENT '检查时间',
	`P_TYPE`			VARCHAR(32)	 COMMENT '隐患类型(预防、纠正)',
	`C_DEPT`			VARCHAR(200)	COMMENT '隐患所在区域/部门',
	`P_LEVEL`			VARCHAR(32)	 COMMENT '隐患等级',
	`C_MEASURE`			VARCHAR(2000)	 COMMENT '整改措施',
	`C_RESPONSIBLE`			VARCHAR(300)	 COMMENT '整改部门',
	`T_RECTIFICATION`			DATE	 COMMENT '要求整改日期',
	`C_PLANT`			VARCHAR(2000)	 COMMENT '治理方案',
	`C_ACCEPTANCE_DEPT`		VARCHAR(300)			COMMENT '验收部门',
	`C_ACCEPTANCE`			VARCHAR(300)	 COMMENT '验收人',
	`T_ACCEPTANCE`		DATE			COMMENT '验收时间',
	`B_FINISH`			CHAR(1)		COMMENT '隐患闭环情况',
	`R_CREATE`			INT(11)	 COMMENT '创建人编号',
	`S_CREATE`			VARCHAR(50)	 COMMENT '创建人',
	`T_CREATE`			DATETIME	 COMMENT '创建时间',
	`R_UPDATE`			INT(11)	 COMMENT '更新人编号',
	`S_UPDATE`			VARCHAR(50)	 COMMENT '更新人',
	`T_UPDATE`			TIMESTAMP	 COMMENT '更新时间',
	`R_TENANT`			INT(11)	 COMMENT '租户编号',
	`S_TENANT`			VARCHAR(300)	 COMMENT '租户名称',
	`P_TENANT`			CHAR(1)	 COMMENT '租户类型',
	`N_STATE`			INT	 COMMENT '状态',
	`B_DELETE`			CHAR(1)	 COMMENT '删除标志',
	`N_INDEX`			INT	 COMMENT '排序',
	`N_VERSION`			INT	 COMMENT '版本',
	PRIMARY KEY  (`SID`)
);


-- 隐患汇总登记台帐模板配置:
DROP TABLE IF EXISTS SSM_STDTMP_FILE_06_ITEM;
DROP TABLE IF EXISTS SSM_STDTMP_FILE_06;
CREATE TABLE SSM_STDTMP_FILE_06
(

	`SID`		INT(11) 	NOT NULL auto_increment COMMENT '自增主键',
	`R_TMPFILE`  int(11) NOT NULL,
	`C_NAME`			VARCHAR(300)	 COMMENT '存在问题',
	`C_EXAMINER`			VARCHAR(300)	 COMMENT '检查人',
	`T_EXAMINE`			DATE	 COMMENT '检查时间',
	`P_TYPE`			VARCHAR(32)	 COMMENT '隐患类型(预防、纠正)',
	`C_DEPT`			VARCHAR(200)	COMMENT '隐患所在区域/部门',
	`P_LEVEL`			VARCHAR(32)	 COMMENT '隐患等级',
	`C_MEASURE`			VARCHAR(2000)	 COMMENT '整改措施',
	`C_RESPONSIBLE`			VARCHAR(300)	 COMMENT '整改部门',
	`T_RECTIFICATION`			DATE	 COMMENT '要求整改日期',
	`C_PLANT`			VARCHAR(2000)	 COMMENT '治理方案',
	`C_ACCEPTANCE_DEPT`		VARCHAR(300)			COMMENT '验收部门',
	`C_ACCEPTANCE`			VARCHAR(300)	 COMMENT '验收人',
	`T_ACCEPTANCE`		DATE			COMMENT '验收时间',
	`B_FINISH`			CHAR(1)		COMMENT '隐患闭环情况',
	`R_CREATE`			INT(11)	 COMMENT '创建人编号',
	`S_CREATE`			VARCHAR(50)	 COMMENT '创建人',
	`T_CREATE`			DATETIME	 COMMENT '创建时间',
	`R_UPDATE`			INT(11)	 COMMENT '更新人编号',
	`S_UPDATE`			VARCHAR(50)	 COMMENT '更新人',
	`T_UPDATE`			TIMESTAMP	 COMMENT '更新时间',
	`R_TENANT`			INT(11)	 COMMENT '租户编号',
	`S_TENANT`			VARCHAR(300)	 COMMENT '租户名称',
	`P_TENANT`			CHAR(1)	 COMMENT '租户类型',
	`N_STATE`			INT	 COMMENT '状态',
	`B_DELETE`			CHAR(1)	 COMMENT '删除标志',
	`N_INDEX`			INT	 COMMENT '排序',
	`N_VERSION`			INT	 COMMENT '版本',
	PRIMARY KEY  (`SID`)
);