ALTER TABLE `ssm_stdtmp_file`
ADD COLUMN `N_COUNT`  int(11) NULL DEFAULT 0 COMMENT '记录文件数量' AFTER `R_SOURCE`;

ALTER TABLE `ssm_stdtmp_folder`
ADD COLUMN `N_COUNT`  int(11) NULL DEFAULT 0 COMMENT '记录文件数量' AFTER `R_SOURCE`;
