/*制度文件待办视图*/
CREATE OR REPLACE  VIEW TODO_STDTMP_FILE_01 AS
    SELECT * FROM
    SSM_STDTMP_FILE_01
    WHERE SID NOT IN (SELECT R_TMPFILE_01 FROM ssm_stdtmp_file_01_item WHERE YEAR(T_DATE_01) = YEAR(NOW())
    AND SID NOT IN (select R_SID from sys_todo where C_CONTROL='STDFILE01')
);

/*隐患排查待办视图*/
CREATE OR REPLACE VIEW TODO_STDTMP_FILE_06 AS
    SELECT * FROM SSM_STDTMP_FILE_06
    WHERE DATEDIFF(T_RECTIFICATION, NOW())<=90 AND B_FINISH = '0'
    AND SID NOT IN (
        -- 排除已创建待办的记录
        select R_SID from sys_todo where C_CONTROL='STDFILE06'
    )
;
