-- 待办表:

DROP TABLE IF EXISTS SYS_TODO;
CREATE TABLE SYS_TODO
(

	`SID`		INT(11) 	NOT NULL auto_increment COMMENT '自增主键',
	`C_TITLE`			VARCHAR(500)	 COMMENT '标题',
	`C_URL`				VARCHAR(500)	 COMMENT 'URL地址',
	`T_BEGIN`			DATETIME	 COMMENT '开始时间',
	`T_END`				DATETIME	 COMMENT '结束时间',
	`C_CONTROL`			VARCHAR(100)	 COMMENT '控制器',
	`R_SID`				INT(11)	 COMMENT 'SID',
	`R_CREATE`			INT(11)	 COMMENT '创建人编号',
	`S_CREATE`			VARCHAR(50)	 COMMENT '创建人',
	`T_CREATE`			DATETIME	 COMMENT '创建时间',
	`R_UPDATE`			INT(11)	 COMMENT '更新人编号',
	`S_UPDATE`			VARCHAR(50)	 COMMENT '更新人',
	`T_UPDATE`			TIMESTAMP	 COMMENT '更新时间',
	`R_TENANT`			INT(11)	 COMMENT '租户编号',
	`S_TENANT`			VARCHAR(300)	 COMMENT '租户名称',
	`P_TENANT`			CHAR(1)	 COMMENT '租户类型',
	`N_STATE`			INT	 COMMENT '状态',
	`B_DELETE`			CHAR(1)	 COMMENT '删除标志',
	`N_INDEX`			INT	 COMMENT '排序',
	`N_VERSION`			INT	 COMMENT '版本',
	PRIMARY KEY  (`SID`)
);


-- 已办表:

DROP TABLE IF EXISTS SYS_DONE;
CREATE TABLE SYS_DONE
(

	`SID`		INT(11) 	NOT NULL auto_increment COMMENT '自增主键',
	`C_TITLE`			VARCHAR(500)	 COMMENT '标题',
	`C_URL`				VARCHAR(500)	 COMMENT 'URL地址',
	`T_BEGIN`			DATETIME	 COMMENT '开始时间',
	`T_END`				DATETIME	 COMMENT '结束时间',
	`C_CONTROL`			VARCHAR(100)	 COMMENT '控制器',
	`R_SID`				INT(11)	 COMMENT 'SID',
	`R_CREATE`			INT(11)	 COMMENT '创建人编号',
	`S_CREATE`			VARCHAR(50)	 COMMENT '创建人',
	`T_CREATE`			DATETIME	 COMMENT '创建时间',
	`R_UPDATE`			INT(11)	 COMMENT '更新人编号',
	`S_UPDATE`			VARCHAR(50)	 COMMENT '更新人',
	`T_UPDATE`			TIMESTAMP	 COMMENT '更新时间',
	`R_TENANT`			INT(11)	 COMMENT '租户编号',
	`S_TENANT`			VARCHAR(300)	 COMMENT '租户名称',
	`P_TENANT`			CHAR(1)	 COMMENT '租户类型',
	`N_STATE`			INT	 COMMENT '状态',
	`B_DELETE`			CHAR(1)	 COMMENT '删除标志',
	`N_INDEX`			INT	 COMMENT '排序',
	`N_VERSION`			INT	 COMMENT '版本',
	PRIMARY KEY  (`SID`)
);

-- 通知公告表:
DROP TABLE IF EXISTS SSM_NOTICE;
CREATE TABLE SSM_NOTICE
(
  `SID`       INT(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `C_TITLE`   INT(11) COMMENT '标题',
  `C_CONTENT` TEXT COMMENT '内容',
  `T_BEGIN`   DATETIME COMMENT '生效时间起',
  `T_END`     DATETIME COMMENT '生效时间止',
  `N_READER`  INT COMMENT '已阅人数',
  `R_PUBLISH`  INT(11) COMMENT '发布人SID',
  `S_PUBLISH`  VARCHAR(300) COMMENT '发布人名称',
  `T_PUBLISH`  DATETIME COMMENT '发布时间',
  `R_CREATE`  INT(11) COMMENT '创建人编号',
  `S_CREATE`  VARCHAR(50) COMMENT '创建人',
  `T_CREATE`  DATETIME COMMENT '创建时间',
  `R_UPDATE`  INT(11) COMMENT '更新人编号',
  `S_UPDATE`  VARCHAR(50) COMMENT '更新人',
  `T_UPDATE`  TIMESTAMP COMMENT '更新时间',
  `R_TENANT`  INT(11) COMMENT '租户编号',
  `S_TENANT`  VARCHAR(300) COMMENT '租户名称',
  `P_TENANT`  CHAR(1) COMMENT '租户类型',
  `N_STATE`   INT COMMENT '状态',
  `B_DELETE`  CHAR(1) COMMENT '删除标志',
  `N_INDEX`   INT COMMENT '排序',
  `N_VERSION` INT COMMENT '版本',
  PRIMARY KEY (`SID`)
);