ALTER TABLE `sys_stdtmp_file`
    ADD COLUMN `R_TEMPLATE` INT NULL DEFAULT NULL COMMENT '所属模板' AFTER `C_DESC`;


ALTER TABLE `ssms`.`sys_tenant_g`
  ADD COLUMN `P_LEVEL` VARCHAR(32) NULL   COMMENT '行政等级编号' AFTER `S_COUNTY`,
  ADD COLUMN `S_LEVEL` VARCHAR(100) NULL   COMMENT '行政等级' AFTER `P_LEVEL`;

ALTER TABLE `ssm_stdtmp_folder`
    CHANGE COLUMN `R_TENANT` `R_TENANT` INT(11) NULL DEFAULT NULL COMMENT '租户编号' AFTER `SID`,
    CHANGE COLUMN `S_TENANT` `S_TENANT` VARCHAR(300) NULL DEFAULT NULL COMMENT '租户编号' AFTER `R_TENANT`,
    CHANGE COLUMN `P_TENANT` `P_TENANT` CHAR(1) NULL DEFAULT NULL COMMENT '租户编号' AFTER `S_TENANT`,
    ADD COLUMN `P_PROFESSION` INT NULL DEFAULT NULL COMMENT '所属专业ID' AFTER `R_TEMPLATE`;


ALTER TABLE `ssm_stdtmp_file`
    CHANGE COLUMN `R_TENANT` `R_TENANT` INT(11) NULL DEFAULT NULL COMMENT '租户编号' AFTER `SID`,
    CHANGE COLUMN `S_TENANT` `S_TENANT` VARCHAR(300) NULL DEFAULT NULL COMMENT '租户编号' AFTER `R_TENANT`,
    CHANGE COLUMN `P_TENANT` `P_TENANT` CHAR(1) NULL DEFAULT NULL COMMENT '租户编号' AFTER `S_TENANT`,
    ADD COLUMN `R_TEMPLATE` INT NULL DEFAULT NULL COMMENT '所属模板ID' AFTER `P_TENANT`,
    ADD COLUMN `P_PROFESSION` INT NULL DEFAULT NULL COMMENT '所属专业ID' AFTER `R_TEMPLATE`;

ALTER TABLE `ssm_stdtmp_file_01`
    CHANGE COLUMN `R_TENANT` `R_TENANT` INT(11) NULL DEFAULT NULL COMMENT '租户编号' AFTER `SID`,
    CHANGE COLUMN `S_TENANT` `S_TENANT` VARCHAR(300) NULL DEFAULT NULL COMMENT '租户编号' AFTER `R_TENANT`,
    CHANGE COLUMN `P_TENANT` `P_TENANT` CHAR(1) NULL DEFAULT NULL COMMENT '租户编号' AFTER `S_TENANT`,
    ADD COLUMN `R_TEMPLATE` INT NULL DEFAULT NULL COMMENT '所属模板ID' AFTER `P_TENANT`,
    ADD COLUMN `P_PROFESSION` INT NULL DEFAULT NULL COMMENT '所属专业ID' AFTER `R_TEMPLATE`,
    ADD COLUMN `R_TMPFOLDER` INT NULL DEFAULT NULL COMMENT '所属模板目录' AFTER `R_TEMPLATE`;

ALTER TABLE `ssm_stdtmp_file_01_ITEM`
    CHANGE COLUMN `R_TENANT` `R_TENANT` INT(11) NULL DEFAULT NULL COMMENT '租户编号' AFTER `SID`,
    CHANGE COLUMN `S_TENANT` `S_TENANT` VARCHAR(300) NULL DEFAULT NULL COMMENT '租户编号' AFTER `R_TENANT`,
    CHANGE COLUMN `P_TENANT` `P_TENANT` CHAR(1) NULL DEFAULT NULL COMMENT '租户编号' AFTER `S_TENANT`,
    ADD COLUMN `R_TEMPLATE` INT NULL DEFAULT NULL COMMENT '所属模板ID' AFTER `P_TENANT`,
    ADD COLUMN `P_PROFESSION` INT NULL DEFAULT NULL COMMENT '所属专业ID' AFTER `R_TEMPLATE`,
    ADD COLUMN `R_TMPFOLDER` INT NULL DEFAULT NULL COMMENT '所属模板目录' AFTER `R_TEMPLATE`;

ALTER TABLE `ssm_stdtmp_file_02`
    CHANGE COLUMN `R_TENANT` `R_TENANT` INT(11) NULL DEFAULT NULL COMMENT '租户编号' AFTER `SID`,
    CHANGE COLUMN `S_TENANT` `S_TENANT` VARCHAR(300) NULL DEFAULT NULL COMMENT '租户编号' AFTER `R_TENANT`,
    CHANGE COLUMN `P_TENANT` `P_TENANT` CHAR(1) NULL DEFAULT NULL COMMENT '租户编号' AFTER `S_TENANT`,
    ADD COLUMN `R_TEMPLATE` INT NULL DEFAULT NULL COMMENT '所属模板ID' AFTER `P_TENANT`,
    ADD COLUMN `P_PROFESSION` INT NULL DEFAULT NULL COMMENT '所属专业ID' AFTER `R_TEMPLATE`,
    ADD COLUMN `R_TMPFOLDER` INT NULL DEFAULT NULL COMMENT '所属模板目录' AFTER `R_TEMPLATE`;

ALTER TABLE `ssm_stdtmp_file_03`
    CHANGE COLUMN `R_TENANT` `R_TENANT` INT(11) NULL DEFAULT NULL COMMENT '租户编号' AFTER `SID`,
    CHANGE COLUMN `S_TENANT` `S_TENANT` VARCHAR(300) NULL DEFAULT NULL COMMENT '租户编号' AFTER `R_TENANT`,
    CHANGE COLUMN `P_TENANT` `P_TENANT` CHAR(1) NULL DEFAULT NULL COMMENT '租户编号' AFTER `S_TENANT`,
    ADD COLUMN `R_TEMPLATE` INT NULL DEFAULT NULL COMMENT '所属模板ID' AFTER `P_TENANT`,
    ADD COLUMN `P_PROFESSION` INT NULL DEFAULT NULL COMMENT '所属专业ID' AFTER `R_TEMPLATE`,
    ADD COLUMN `R_TMPFOLDER` INT NULL DEFAULT NULL COMMENT '所属模板目录' AFTER `R_TEMPLATE`;

ALTER TABLE `ssm_stdtmp_file_04`
    CHANGE COLUMN `R_TENANT` `R_TENANT` INT(11) NULL DEFAULT NULL COMMENT '租户编号' AFTER `SID`,
    CHANGE COLUMN `S_TENANT` `S_TENANT` VARCHAR(300) NULL DEFAULT NULL COMMENT '租户编号' AFTER `R_TENANT`,
    CHANGE COLUMN `P_TENANT` `P_TENANT` CHAR(1) NULL DEFAULT NULL COMMENT '租户编号' AFTER `S_TENANT`,
    ADD COLUMN `R_TEMPLATE` INT NULL DEFAULT NULL COMMENT '所属模板ID' AFTER `P_TENANT`,
    ADD COLUMN `P_PROFESSION` INT NULL DEFAULT NULL COMMENT '所属专业ID' AFTER `R_TEMPLATE`,
    ADD COLUMN `R_TMPFOLDER` INT NULL DEFAULT NULL COMMENT '所属模板目录' AFTER `R_TEMPLATE`;

ALTER TABLE `ssm_stdtmp_file_06`
    CHANGE COLUMN `R_TENANT` `R_TENANT` INT(11) NULL DEFAULT NULL COMMENT '租户编号' AFTER `SID`,
    CHANGE COLUMN `S_TENANT` `S_TENANT` VARCHAR(300) NULL DEFAULT NULL COMMENT '租户编号' AFTER `R_TENANT`,
    CHANGE COLUMN `P_TENANT` `P_TENANT` CHAR(1) NULL DEFAULT NULL COMMENT '租户编号' AFTER `S_TENANT`,
    ADD COLUMN `R_TEMPLATE` INT NULL DEFAULT NULL COMMENT '所属模板ID' AFTER `P_TENANT`,
    ADD COLUMN `P_PROFESSION` INT NULL DEFAULT NULL COMMENT '所属专业ID' AFTER `R_TEMPLATE`,
    ADD COLUMN `R_TMPFOLDER` INT NULL DEFAULT NULL COMMENT '所属模板目录' AFTER `R_TEMPLATE`;

ALTER TABLE `ssm_stdtmp_file_07`
    CHANGE COLUMN `R_TENANT` `R_TENANT` INT(11) NULL DEFAULT NULL COMMENT '租户编号' AFTER `SID`,
    CHANGE COLUMN `S_TENANT` `S_TENANT` VARCHAR(300) NULL DEFAULT NULL COMMENT '租户编号' AFTER `R_TENANT`,
    CHANGE COLUMN `P_TENANT` `P_TENANT` CHAR(1) NULL DEFAULT NULL COMMENT '租户编号' AFTER `S_TENANT`,
    ADD COLUMN `R_TEMPLATE` INT NULL DEFAULT NULL COMMENT '所属模板ID' AFTER `P_TENANT`,
    ADD COLUMN `P_PROFESSION` INT NULL DEFAULT NULL COMMENT '所属专业ID' AFTER `R_TEMPLATE`,
    ADD COLUMN `R_TMPFOLDER` INT NULL DEFAULT NULL COMMENT '所属模板目录' AFTER `R_TEMPLATE`;

ALTER TABLE `ssm_stdtmp_file_08`
    CHANGE COLUMN `R_TENANT` `R_TENANT` INT(11) NULL DEFAULT NULL COMMENT '租户编号' AFTER `SID`,
    CHANGE COLUMN `S_TENANT` `S_TENANT` VARCHAR(300) NULL DEFAULT NULL COMMENT '租户编号' AFTER `R_TENANT`,
    CHANGE COLUMN `P_TENANT` `P_TENANT` CHAR(1) NULL DEFAULT NULL COMMENT '租户编号' AFTER `S_TENANT`,
    ADD COLUMN `R_TEMPLATE` INT NULL DEFAULT NULL COMMENT '所属模板ID' AFTER `P_TENANT`,
    ADD COLUMN `P_PROFESSION` INT NULL DEFAULT NULL COMMENT '所属专业ID' AFTER `R_TEMPLATE`,
    ADD COLUMN `R_TMPFOLDER` INT NULL DEFAULT NULL COMMENT '所属模板目录' AFTER `R_TEMPLATE`;

ALTER TABLE `ssm_stdtmp_file_09`
    CHANGE COLUMN `R_TENANT` `R_TENANT` INT(11) NULL DEFAULT NULL COMMENT '租户编号' AFTER `SID`,
    CHANGE COLUMN `S_TENANT` `S_TENANT` VARCHAR(300) NULL DEFAULT NULL COMMENT '租户编号' AFTER `R_TENANT`,
    CHANGE COLUMN `P_TENANT` `P_TENANT` CHAR(1) NULL DEFAULT NULL COMMENT '租户编号' AFTER `S_TENANT`,
    ADD COLUMN `R_TEMPLATE` INT NULL DEFAULT NULL COMMENT '所属模板ID' AFTER `P_TENANT`,
    ADD COLUMN `P_PROFESSION` INT NULL DEFAULT NULL COMMENT '所属专业ID' AFTER `R_TEMPLATE`,
    ADD COLUMN `R_TMPFOLDER` INT NULL DEFAULT NULL COMMENT '所属模板目录' AFTER `R_TEMPLATE`;

drop table if exists ssm_stdtmp_file_arch;
create table ssm_stdtmp_file_arch like ssm_stdtmp_file;
drop table if exists ssm_stdtmp_folder_arch;
create table ssm_stdtmp_folder_arch like ssm_stdtmp_folder;
drop table if exists ssm_stdtmp_file_01_arch;
create table ssm_stdtmp_file_01_arch like ssm_stdtmp_file_01;
drop table if exists ssm_stdtmp_file_01_item_arch;
create table ssm_stdtmp_file_01_item_arch like ssm_stdtmp_file_01_item;
drop table if exists ssm_stdtmp_file_02_arch;
create table ssm_stdtmp_file_02_arch like ssm_stdtmp_file_02;
drop table if exists ssm_stdtmp_file_03_arch;
create table ssm_stdtmp_file_03_arch like ssm_stdtmp_file_03;
drop table if exists ssm_stdtmp_file_04_arch;
create table ssm_stdtmp_file_04_arch like ssm_stdtmp_file_04;
drop table if exists ssm_stdtmp_file_06_arch;
create table ssm_stdtmp_file_06_arch like ssm_stdtmp_file_06;
drop table if exists ssm_stdtmp_file_07_arch;
create table ssm_stdtmp_file_07_arch like ssm_stdtmp_file_07;
drop table if exists ssm_stdtmp_file_08_arch;
create table ssm_stdtmp_file_08_arch like ssm_stdtmp_file_08;
drop table if exists ssm_stdtmp_file_09_arch;
create table ssm_stdtmp_file_09_arch like ssm_stdtmp_file_09;


ALTER TABLE `ssm_stdtmp_folder_arch`
    ADD COLUMN `UID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '归档用主键' FIRST,
    ADD COLUMN `N_ARCH_VERSION` INT(11) NOT NULL DEFAULT '0' COMMENT '归档版本' AFTER `UID`,
    CHANGE COLUMN `SID` `SID` INT(11) NULL DEFAULT NULL COMMENT '自增主键' AFTER `N_ARCH_VERSION`,
    DROP PRIMARY KEY,
    ADD PRIMARY KEY (`UID`);
ALTER TABLE `ssm_stdtmp_file_arch`
    ADD COLUMN `UID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '归档用主键' FIRST,
    ADD COLUMN `N_ARCH_VERSION` INT(11) NOT NULL DEFAULT '0' COMMENT '归档版本' AFTER `UID`,
    CHANGE COLUMN `SID` `SID` INT(11) NULL DEFAULT NULL COMMENT '自增主键' AFTER `N_ARCH_VERSION`,
    DROP PRIMARY KEY,
    ADD PRIMARY KEY (`UID`);
ALTER TABLE `ssm_stdtmp_file_01_arch`
    ADD COLUMN `UID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '归档用主键' FIRST,
    ADD COLUMN `N_ARCH_VERSION` INT(11) NOT NULL DEFAULT '0' COMMENT '归档版本' AFTER `UID`,
    CHANGE COLUMN `SID` `SID` INT(11) NULL DEFAULT NULL COMMENT '自增主键' AFTER `N_ARCH_VERSION`,
    DROP PRIMARY KEY,
    ADD PRIMARY KEY (`UID`);
ALTER TABLE `ssm_stdtmp_file_01_item_arch`
    ADD COLUMN `UID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '归档用主键' FIRST,
    ADD COLUMN `N_ARCH_VERSION` INT(11) NOT NULL DEFAULT '0' COMMENT '归档版本' AFTER `UID`,
    CHANGE COLUMN `SID` `SID` INT(11) NULL DEFAULT NULL COMMENT '自增主键' AFTER `N_ARCH_VERSION`,
    DROP PRIMARY KEY,
    ADD PRIMARY KEY (`UID`);
ALTER TABLE `ssm_stdtmp_file_02_arch`
    ADD COLUMN `UID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '归档用主键' FIRST,
    ADD COLUMN `N_ARCH_VERSION` INT(11) NOT NULL DEFAULT '0' COMMENT '归档版本' AFTER `UID`,
    CHANGE COLUMN `SID` `SID` INT(11) NULL DEFAULT NULL COMMENT '自增主键' AFTER `N_ARCH_VERSION`,
    DROP PRIMARY KEY,
    ADD PRIMARY KEY (`UID`);
ALTER TABLE `ssm_stdtmp_file_03_arch`
    ADD COLUMN `UID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '归档用主键' FIRST,
    ADD COLUMN `N_ARCH_VERSION` INT(11) NOT NULL DEFAULT '0' COMMENT '归档版本' AFTER `UID`,
    CHANGE COLUMN `SID` `SID` INT(11) NULL DEFAULT NULL COMMENT '自增主键' AFTER `N_ARCH_VERSION`,
    DROP PRIMARY KEY,
    ADD PRIMARY KEY (`UID`);
ALTER TABLE `ssm_stdtmp_file_04_arch`
    ADD COLUMN `UID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '归档用主键' FIRST,
    ADD COLUMN `N_ARCH_VERSION` INT(11) NOT NULL DEFAULT '0' COMMENT '归档版本' AFTER `UID`,
    CHANGE COLUMN `SID` `SID` INT(11) NULL DEFAULT NULL COMMENT '自增主键' AFTER `N_ARCH_VERSION`,
    DROP PRIMARY KEY,
    ADD PRIMARY KEY (`UID`);
ALTER TABLE `ssm_stdtmp_file_06_arch`
    ADD COLUMN `UID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '归档用主键' FIRST,
    ADD COLUMN `N_ARCH_VERSION` INT(11) NOT NULL DEFAULT '0' COMMENT '归档版本' AFTER `UID`,
    CHANGE COLUMN `SID` `SID` INT(11) NULL DEFAULT NULL COMMENT '自增主键' AFTER `N_ARCH_VERSION`,
    DROP PRIMARY KEY,
    ADD PRIMARY KEY (`UID`);
ALTER TABLE `ssm_stdtmp_file_07_arch`
    ADD COLUMN `UID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '归档用主键' FIRST,
    ADD COLUMN `N_ARCH_VERSION` INT(11) NOT NULL DEFAULT '0' COMMENT '归档版本' AFTER `UID`,
    CHANGE COLUMN `SID` `SID` INT(11) NULL DEFAULT NULL COMMENT '自增主键' AFTER `N_ARCH_VERSION`,
    DROP PRIMARY KEY,
    ADD PRIMARY KEY (`UID`);
ALTER TABLE `ssm_stdtmp_file_08_arch`
    ADD COLUMN `UID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '归档用主键' FIRST,
    ADD COLUMN `N_ARCH_VERSION` INT(11) NOT NULL DEFAULT '0' COMMENT '归档版本' AFTER `UID`,
    CHANGE COLUMN `SID` `SID` INT(11) NULL DEFAULT NULL COMMENT '自增主键' AFTER `N_ARCH_VERSION`,
    DROP PRIMARY KEY,
    ADD PRIMARY KEY (`UID`);
ALTER TABLE `ssm_stdtmp_file_09_arch`
    ADD COLUMN `UID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '归档用主键' FIRST,
    ADD COLUMN `N_ARCH_VERSION` INT(11) NOT NULL DEFAULT '0' COMMENT '归档版本' AFTER `UID`,
    CHANGE COLUMN `SID` `SID` INT(11) NULL DEFAULT NULL COMMENT '自增主键' AFTER `N_ARCH_VERSION`,
    DROP PRIMARY KEY,
    ADD PRIMARY KEY (`UID`);

DELIMITER $$

DROP PROCEDURE IF EXISTS SP_GETSEQVALUE$$
CREATE PROCEDURE `SP_GETSEQVALUE`(
    IN C_NAME VARCHAR(32),
    IN N_LENGTH INT,
    INOUT C_PATTERN VARCHAR(200)
)
BEGIN
    DECLARE STR_RESULT VARCHAR(200);
    DECLARE STR_NAME VARCHAR(200) DEFAULT UPPER(C_NAME);

    START TRANSACTION;

    -- 查询当前的值
    SELECT CAST(A.N_VALUE AS CHAR) INTO STR_RESULT FROM GEN_SEQUENCE A WHERE A.C_NAME=STR_NAME;
    

    -- 如果当前值不存在则应该要插入数据
    IF STR_RESULT IS NULL THEN
        INSERT INTO `GEN_SEQUENCE`(C_NAME) VALUES(STR_NAME);
        -- 再次查询当前的值
         SELECT CAST(A.N_VALUE AS CHAR) INTO STR_RESULT FROM GEN_SEQUENCE A WHERE A.C_NAME=STR_NAME;
    END IF;

    IF N_LENGTH > LENGTH(STR_RESULT) THEN
        SET STR_RESULT=LPAD(STR_RESULT, N_LENGTH, '0');
    END IF;
    SET C_PATTERN = REPLACE(C_PATTERN, '@', STR_RESULT);

    -- 更新当前的值
    UPDATE `GEN_SEQUENCE`
    SET `N_VALUE` = `N_VALUE`+`N_STEP`;

    COMMIT;
END$$

DELIMITER ;