 /*通知公告*/		
CREATE OR REPLACE VIEW V_NOTICE AS
 SELECT T1.*,T2.R_RECEIVER,T2.S_RECEIVER,T2.Z_TYPE 
 FROM SYS_NOTICE T1 
 INNER JOIN SYS_NOTICE_RECEIVER T2 ON T1.SID=T2.R_NOTICE 
 WHERE 
 T1.R_PUBLISH IS NOT NULL 
 ORDER BY T1.T_PUBLISH DESC;
 
/*制度文件待办视图*/
CREATE OR REPLACE  VIEW TODO_STDTMP_FILE_01
    AS
(SELECT * FROM SSM_STDTMP_FILE_01 WHERE SID NOT IN ( SELECT R_TMPFILE_01 FROM ssm_stdtmp_file_01_item WHERE YEAR(T_DATE_01) = YEAR(NOW()) ));

/*隐患排查待办视图*/
CREATE OR REPLACE  VIEW  TODO_STDTMP_FILE_06 
    AS
(SELECT * FROM SSM_STDTMP_FILE_06 WHERE DATEDIFF(T_ACCEPTANCE,NOW())=90 AND B_FINISH = '0');

